package util;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.io.FileUtils;
import org.apache.pdfbox.multipdf.PDFMergerUtility;

import com.itextpdf.text.pdf.AcroFields;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;

import sun.misc.BASE64Encoder;

public class CreatePDFUtil {

	public static String newPdf(String root, String inputFileName, String outputFileName, Map<String, String> dataMap)
			throws Exception {
		OutputStream os = null;
		PdfStamper ps = null;
		PdfReader reader = null;
		SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd");
		String fileStr = format.format(new Date());
		try {
			// 判断当前文件夹是否存在
			File file = new File(root + fileStr);
			if (!file.exists()) {
				File dirf = new File(root);
				File files[] = dirf.listFiles();
				for (File f : files) {
					if (f.isDirectory()) { // 判断是否为文件夹
						FileUtils.deleteDirectory(f);
					} else {
						f.delete();
					}
				}
				file.mkdirs();
			}
			outputFileName = root + fileStr + "/" + outputFileName;
			os = new FileOutputStream(new File(outputFileName));
			// 2 读入pdf表单
			reader = new PdfReader(inputFileName);
			// 3 根据表单生成一个新的pdf
			ps = new PdfStamper(reader, os);
			// 4 获取pdf表单
			AcroFields form = ps.getAcroFields();
			// 5给表单添加中文字体 这里采用系统字体。不设置的话，中文可能无法显示
			BaseFont bf = BaseFont.createFont("STSong-Light", "UniGB-UCS2-H", BaseFont.NOT_EMBEDDED);
			form.addSubstitutionFont(bf);
			// 7遍历data 给pdf表单表格赋值
			for (String key : dataMap.keySet()) {
				form.setField(key, dataMap.get(key));
			}
			ps.setFormFlattening(true);
		} finally {
			try {
				ps.close();
				reader.close();
				os.close();
			} catch (Exception e) {
				e.printStackTrace();
			}
		}
		return fileStr;
	}

	/**
	 *      *
	 * <p>
	 * 将文件转成base64 字符串
	 * </p>
	 *      * @param path 文件路径      
	 */
	public static String encodeBase64File(String urlStr, String outurl) throws Exception {
		URL url = new URL(urlStr);
		InputStream is = url.openStream();
		OutputStream os = new FileOutputStream(outurl);
		byte bf[] = new byte[1024];
		int length = 0;
		while ((length = is.read(bf, 0, 1024)) != -1) {
			os.write(bf, 0, length);
		}
		is.close();
		os.close();
		File file = new File(outurl);
		FileInputStream inputFile = new FileInputStream(file);
		byte[] buffer = new byte[(int) file.length()];
		inputFile.read(buffer);
		inputFile.close();
		file.delete();
		return new BASE64Encoder().encode(buffer);
	}

	@SuppressWarnings("deprecation")
	public static String PDFMerger(String root, List<String> files, String outFileName) throws Exception {
		if (files != null && files.size() > 0) {
			PDFMergerUtility mergePdf = new PDFMergerUtility();
			for (int i = 0; i < files.size(); i++) {
				mergePdf.addSource(files.get(i));
				if (i == (files.size() - 1)) {
					String furl = files.get(i);
					furl = furl.substring(0, furl.lastIndexOf("/"));
					furl = furl.substring(furl.lastIndexOf("/") + 1);
					outFileName = root + furl + "/" + outFileName;
				}
			}
			mergePdf.setDestinationFileName(outFileName);
			mergePdf.mergeDocuments();
		}
		outFileName = outFileName.substring(outFileName.lastIndexOf("printTemplate"));
		return outFileName;
	}

	public static void main(String[] args) {
		try {
			Map<String, String> dataMap = new HashMap<String, String>();
			int num = 14;
			if (num == 0) {// 健康档案封面
				dataMap.put("num1", "1");
				dataMap.put("num2", "2");
				dataMap.put("num3", "3");
				dataMap.put("num4", "4");
				dataMap.put("num5", "5");
				dataMap.put("num6", "6");
				dataMap.put("num7", "7");
				dataMap.put("num8", "8");
				dataMap.put("num9", "9");
				dataMap.put("num10", "0");
				dataMap.put("num11", "1");
				dataMap.put("num12", "2");
				dataMap.put("name", "粟寿伟");
				dataMap.put("address", "四川省开江县普安镇九石坎村２组６５号");
				dataMap.put("address1", "四川省开江县普安镇九石坎村２组６５号");
				dataMap.put("phoneno", "18982811362");
				dataMap.put("countyname", "普安镇");
				dataMap.put("vcname", "九石坎");
				dataMap.put("fileunit", "开江县普安镇卫生院");
				dataMap.put("fileuser", "吴法政");
				dataMap.put("doctor", "吴法政");
				dataMap.put("filedate", "2018年04月25日");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/healthFileCover.pdf", "1.pdf",
						dataMap);
			} else if (num == 1) {// B超
				dataMap.put("name", "测试");
				dataMap.put("sex", "男");
				dataMap.put("age", "30");
				dataMap.put("code", "111111111111");
				dataMap.put("field244", "内容");
				dataMap.put("field245", "内容");
				dataMap.put("field250", "内容");
				dataMap.put("field1", "2018年04月25日");
				dataMap.put("field210", CreatePDFUtil.encodeBase64File(
						"http://iservice.oss-cn-beijing.aliyuncs.com/healthcare/bchao/2019/03/24/018782230622_00001.jpg",
						"D:/test.png"));
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/bsuper1.pdf", "1.pdf", dataMap);
			} else if (num == 2) {// 心电图报告
				dataMap.put("name", "测试");
				dataMap.put("sex", "男");
				dataMap.put("age", "30");
				dataMap.put("code", "111111111111");
				dataMap.put("ecgStr", "内容");
				dataMap.put("field249", "内容");
				dataMap.put("field1", "2018年04月25日");
				dataMap.put("field246", CreatePDFUtil.encodeBase64File(
						"http://iservice.oss-cn-beijing.aliyuncs.com/healthcare/bchao/2019/03/24/018782230622_00001.jpg",
						"D:/test.png"));
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/elediogram.pdf", "1.pdf", dataMap);
			} else if (num == 3) {// 尿常规报告
				dataMap.put("name", "测试");
				dataMap.put("sex", "男");
				dataMap.put("age", "30");
				dataMap.put("code", "111111111111");
				dataMap.put("fileunit", "单位");
				dataMap.put("field101", "<=0.2mg/dL");
				dataMap.put("field258", "<=0.2mg/dL");
				dataMap.put("hfield101", "<=0.2mg/dL");
				dataMap.put("field102", "<=0.2mg/dL");
				dataMap.put("field259", "<=0.2mg/dL");
				dataMap.put("hfield102", "<=0.2mg/dL");
				dataMap.put("field237", "<=0.2mg/dL");
				dataMap.put("field260", "<=0.2mg/dL");
				dataMap.put("hfield237", "<=0.2mg/dL");
				dataMap.put("field238", "<=0.2mg/dL");
				dataMap.put("field261", "<=0.2mg/dL");
				dataMap.put("hfield238", "<=0.2mg/dL");
				dataMap.put("field104", "<=0.2mg/dL");
				dataMap.put("field262", "<=0.2mg/dL");
				dataMap.put("hfield104", "<=0.2mg/dL");
				dataMap.put("field103", "<=0.2mg/dL");
				dataMap.put("field263", "<=0.2mg/dL");
				dataMap.put("hfield103", "<=0.2mg/dL");
				dataMap.put("field239", "<=0.2mg/dL");
				dataMap.put("field264", "<=0.2mg/dL");
				dataMap.put("hfield239", "<=0.2mg/dL");
				dataMap.put("field240", "<=0.2mg/dL");
				dataMap.put("field265", "<=0.2mg/dL");
				dataMap.put("hfield240", "<=0.2mg/dL");
				dataMap.put("field241", "<=0.2mg/dL");
				dataMap.put("field266", "<=0.2mg/dL");
				dataMap.put("hfield241", "<=0.2mg/dL");
				dataMap.put("field242", "<=0.2mg/dL");
				dataMap.put("field267", "<=0.2mg/dL");
				dataMap.put("hfield242", "<=0.2mg/dL");
				dataMap.put("field247", "山意思");
				dataMap.put("field1", "2018年04月25日");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/urine.pdf", "1.pdf", dataMap);
			} else if (num == 4) {// 血常规报告
				dataMap.put("name", "测试");
				dataMap.put("sex", "男");
				dataMap.put("age", "30");
				dataMap.put("code", "111111111111");
				dataMap.put("fileunit", "单位");
				dataMap.put("field97", "302.02");
				dataMap.put("hfield97", "正常");
				dataMap.put("field98", "302.02");
				dataMap.put("hfield98", "正常");
				dataMap.put("field222", "302.02");
				dataMap.put("hfield222", "正常");
				dataMap.put("field223", "302.02");
				dataMap.put("hfield223", "正常");
				dataMap.put("field234", "302.02");
				dataMap.put("hfield234", "正常");
				dataMap.put("field235", "302.02");
				dataMap.put("hfield235", "正常");
				dataMap.put("field236", "302.02");
				dataMap.put("hfield236", "正常");
				dataMap.put("field227", "302.02");
				dataMap.put("hfield227", "正常");
				dataMap.put("field228", "302.02");
				dataMap.put("hfield228", "正常");
				dataMap.put("field229", "302.02");
				dataMap.put("hfield229", "正常");
				dataMap.put("field243", "302.02");
				dataMap.put("hfield243", "正常");
				dataMap.put("field230", "302.02");
				dataMap.put("hfield230", "正常");
				dataMap.put("field99", "302.02");
				dataMap.put("hfield99", "正常");
				dataMap.put("field231", "302.02");
				dataMap.put("hfield231", "正常");
				dataMap.put("field232", "302.02");
				dataMap.put("hfield232", "正常");
				dataMap.put("field233", "302.02");
				dataMap.put("hfield233", "正常");
				dataMap.put("field224", "302.02");
				dataMap.put("hfield224", "正常");
				dataMap.put("field225", "302.02");
				dataMap.put("hfield225", "正常");
				dataMap.put("field226", "302.02");
				dataMap.put("hfield226", "正常");
				dataMap.put("field14", "削减元");
				dataMap.put("field1", "2018年04月25日");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/blood.pdf", "1.pdf", dataMap);
			} else if (num == 5) {// 生化报告
				dataMap.put("name", "测试");
				dataMap.put("sex", "男");
				dataMap.put("age", "30");
				dataMap.put("code", "111111111111");
				dataMap.put("fileunit", "单位");
				dataMap.put("field114", "302.02");
				dataMap.put("hfield114", "正常");
				dataMap.put("field115", "302.02");
				dataMap.put("hfield115", "正常");
				dataMap.put("field117", "302.02");
				dataMap.put("hfield117", "正常");
				dataMap.put("field119", "302.02");
				dataMap.put("hfield119", "正常");
				dataMap.put("field120", "302.02");
				dataMap.put("hfield120", "正常");
				dataMap.put("field123", "302.02");
				dataMap.put("hfield123", "正常");
				dataMap.put("field124", "302.02");
				dataMap.put("hfield124", "正常");
				dataMap.put("field106", "302.02");
				dataMap.put("hfield106", "正常");
				dataMap.put("field125", "302.02");
				dataMap.put("hfield125", "正常");
				dataMap.put("field126", "302.02");
				dataMap.put("hfield126", "↑");
				dataMap.put("field248", "削减元");
				dataMap.put("field1", "2018年04月25日");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/biochemical.pdf", "1.pdf", dataMap);
			} else if (num == 6) {// 自理能力
				dataMap.put("name", "测试");
				dataMap.put("idcard", "111111111111");
				dataMap.put("s1", "1");
				dataMap.put("s2", "2");
				dataMap.put("s3", "3");
				dataMap.put("s4", "4");
				dataMap.put("s5", "5");
				dataMap.put("total", "10");
				dataMap.put("field7", "目标");
				dataMap.put("field8", "2019年12月11日");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/selfcare.pdf", "1.pdf", dataMap);
			} else if (num == 7) {// 体检报告(单页)
				dataMap.put("name", "测试");
				dataMap.put("sex", "男");
				dataMap.put("age", "30");
				dataMap.put("code", "111111111111");
				dataMap.put("idcard", "111111111111");
				dataMap.put("address", "地址");
				dataMap.put("field219", "身高175cm体重56kg");
				dataMap.put("field9", "160/180");
				// dataMap.put("field10", "160");
				// 血红蛋白
				dataMap.put("field97", "160");
				dataMap.put("hfield97", "正常");
				// 淋巴细胞百分率
				dataMap.put("field224", "160");
				dataMap.put("hfield224", "正常");
				// 白细胞
				dataMap.put("field98", "160");
				dataMap.put("hfield98", "正常");
				// 中间细胞百分比
				dataMap.put("field225", "160");
				dataMap.put("hfield225", "正常");
				// 血小板
				dataMap.put("field99", "160");
				dataMap.put("hfield99", "正常");
				// 中性粒细胞百分比
				dataMap.put("field226", "160");
				dataMap.put("hfield226", "正常");
				// 红细胞
				dataMap.put("field222", "160");
				dataMap.put("hfield222", "正常");
				// 平均血红蛋白浓度
				dataMap.put("field227", "160");
				dataMap.put("hfield227", "正常");
				// 平均红细胞体积
				dataMap.put("field228", "160");
				dataMap.put("hfield228", "正常");
				// 平均血红蛋白含量
				dataMap.put("field229", "160");
				dataMap.put("hfield229", "正常");
				// 尿蛋白
				dataMap.put("field101", "-");
				// 尿糖
				dataMap.put("field102", "-");
				// 尿酮体
				dataMap.put("field103", "-");
				// 尿潜血
				dataMap.put("field104", "-");
				// 血清谷丙转氨酶
				dataMap.put("field114", "160");
				dataMap.put("hfield114", "正常");
				// 血清谷草转氨酶
				dataMap.put("field115", "160");
				dataMap.put("hfield115", "正常");
				// 总胆红素
				dataMap.put("field117", "160");
				dataMap.put("hfield117", "正常");
				// 血清肌酐
				dataMap.put("field119", "160");
				dataMap.put("hfield119", "正常");
				// 血尿素氮
				dataMap.put("field120", "160");
				dataMap.put("hfield120", "正常");
				// 总胆固醇
				dataMap.put("field123", "160");
				dataMap.put("hfield123", "正常");
				// 甘油三酯
				dataMap.put("field124", "160");
				dataMap.put("hfield124", "正常");
				// 空腹血糖
				dataMap.put("field106", "160");
				dataMap.put("hfield106", "正常");
				// 血清低密度脂蛋白
				dataMap.put("field125", "160");
				dataMap.put("hfield125", "正常");
				// 血清高密度脂蛋白
				dataMap.put("field126", "160");
				dataMap.put("hfield126", "正常");
				dataMap.put("ECG", "ST段改变 其他 820不明心律310左心室高电压742异常Q波(侧壁),请结合临床*** 异常心电图 ***");
				dataMap.put("field77", "160");
				dataMap.put("bsuper", "B超结果");
				dataMap.put("field1", "2018年04月25日");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/mreport1.pdf", "1.pdf", dataMap);
			} else if (num == 8) {// 中医体质
				dataMap.put("name", "测试");
				dataMap.put("num1", "1");
				dataMap.put("num2", "2");
				dataMap.put("num3", "3");
				dataMap.put("num4", "4");
				dataMap.put("num5", "5");
				dataMap.put("num6", "6");
				dataMap.put("num7", "7");
				dataMap.put("num8", "8");
				dataMap.put("num9", "9");
				dataMap.put("num10", "0");
				dataMap.put("num11", "1");
				dataMap.put("num12", "2");
				dataMap.put("field1", "2");
				dataMap.put("field2", "2");
				dataMap.put("field3", "2");
				dataMap.put("field4", "2");
				dataMap.put("field5", "2");
				dataMap.put("field6", "2");
				dataMap.put("field7", "2");
				dataMap.put("field8", "2");
				dataMap.put("field9", "2");
				dataMap.put("field10", "2");
				dataMap.put("field11", "2");
				dataMap.put("field12", "2");
				dataMap.put("field13", "2");
				dataMap.put("field14", "2");
				dataMap.put("field15", "2");
				dataMap.put("field16", "2");
				dataMap.put("field17", "2");
				dataMap.put("field18", "2");
				dataMap.put("field19", "2");
				dataMap.put("field20", "2");
				dataMap.put("field21", "2");
				dataMap.put("field22", "2");
				dataMap.put("field23", "2");
				dataMap.put("field24", "2");
				dataMap.put("field25", "2");
				dataMap.put("field26", "2");
				dataMap.put("field27", "2");
				dataMap.put("field28", "2");
				dataMap.put("field29", "2");
				dataMap.put("field30", "2");
				dataMap.put("field31", "2");
				dataMap.put("field32", "2");
				dataMap.put("field33", "2");
				dataMap.put("field34", "2");
				dataMap.put("field343", "√");
				dataMap.put("field344", "√");
				dataMap.put("field345", "√");
				dataMap.put("field346", "√");
				dataMap.put("field347", "√");
				dataMap.put("field35", "2");
				dataMap.put("field353", "√");
				dataMap.put("field354", "√");
				dataMap.put("field355", "√");
				dataMap.put("field356", "√");
				dataMap.put("field357", "√");
				dataMap.put("field36", "2");
				dataMap.put("field363", "√");
				dataMap.put("field364", "√");
				dataMap.put("field365", "√");
				dataMap.put("field366", "√");
				dataMap.put("field367", "√");
				dataMap.put("field37", "2");
				dataMap.put("field373", "√");
				dataMap.put("field374", "√");
				dataMap.put("field375", "√");
				dataMap.put("field376", "√");
				dataMap.put("field377", "√");
				dataMap.put("field38", "2");
				dataMap.put("field383", "√");
				dataMap.put("field384", "√");
				dataMap.put("field385", "√");
				dataMap.put("field386", "√");
				dataMap.put("field387", "√");
				dataMap.put("field39", "2");
				dataMap.put("field393", "√");
				dataMap.put("field394", "√");
				dataMap.put("field395", "√");
				dataMap.put("field396", "√");
				dataMap.put("field397", "√");
				dataMap.put("field40", "2");
				dataMap.put("field403", "√");
				dataMap.put("field404", "√");
				dataMap.put("field405", "√");
				dataMap.put("field406", "√");
				dataMap.put("field407", "√");
				dataMap.put("field41", "2");
				dataMap.put("field413", "√");
				dataMap.put("field414", "√");
				dataMap.put("field415", "√");
				dataMap.put("field416", "√");
				dataMap.put("field417", "√");
				dataMap.put("field42", "2");
				dataMap.put("field423", "√");
				dataMap.put("field424", "√");
				dataMap.put("field425", "√");
				dataMap.put("field426", "√");
				dataMap.put("field427", "√");
				// 气虚质得分
				dataMap.put("field53", "21");
				// 阳虚质得分
				dataMap.put("field54", "21");
				// 阴虚质得分
				dataMap.put("field55", "21");
				// 痰湿质得分
				dataMap.put("field56", "21");
				// 湿热质得分
				dataMap.put("field57", "21");
				// 血瘀质得分
				dataMap.put("field58", "21");
				// 气郁质得分
				dataMap.put("field59", "21");
				// 特禀质得分
				dataMap.put("field60", "21");
				// 平和质得分
				dataMap.put("field61", "21");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/TCM.pdf", "1.pdf", dataMap);
			} else if (num == 9) {// 体检报告(双面)
				dataMap.put("name", "测试");
				dataMap.put("code", "111111111111");
				dataMap.put("sex", "男");
				dataMap.put("age", "30");
				dataMap.put("field1", "2018年04月25日");
				dataMap.put("field11", "1.7");
				dataMap.put("field12", "1.7");
				dataMap.put("field219", "1.7");
				dataMap.put("hfield219", "正常");
				dataMap.put("field9", "1.7");
				dataMap.put("hfield9", "正常");
				dataMap.put("field10", "1.7");
				dataMap.put("hfield10", "正常");
				dataMap.put("field97", "1.7");
				dataMap.put("hfield97", "正常");
				dataMap.put("field98", "1.7");
				dataMap.put("hfield98", "正常");
				dataMap.put("field222", "1.7");
				dataMap.put("hfield222", "正常");
				dataMap.put("field223", "1.7");
				dataMap.put("hfield223", "正常");
				dataMap.put("field224", "1.7");
				dataMap.put("hfield224", "正常");
				dataMap.put("field225", "1.7");
				dataMap.put("hfield225", "正常");
				dataMap.put("field226", "1.7");
				dataMap.put("hfield226", "正常");
				dataMap.put("field227", "1.7");
				dataMap.put("hfield227", "正常");
				dataMap.put("field228", "1.7");
				dataMap.put("hfield228", "正常");
				dataMap.put("field229", "1.7");
				dataMap.put("hfield229", "正常");
				dataMap.put("field243", "1.7");
				dataMap.put("hfield243", "正常");
				dataMap.put("field230", "1.7");
				dataMap.put("hfield230", "正常");
				dataMap.put("field99", "1.7");
				dataMap.put("hfield99", "正常");
				dataMap.put("field231", "1.7");
				dataMap.put("hfield231", "正常");
				dataMap.put("field232", "1.7");
				dataMap.put("hfield232", "正常");
				dataMap.put("field233", "1.7");
				dataMap.put("hfield233", "正常");
				dataMap.put("field234", "1.7");
				dataMap.put("hfield234", "正常");
				dataMap.put("field235", "1.7");
				dataMap.put("hfield235", "正常");
				dataMap.put("field236", "1.7");
				dataMap.put("hfield236", "正常");
				dataMap.put("field101", "1.7");
				dataMap.put("field258", "<=0.2mg/dL");
				dataMap.put("hfield101", "正常");
				dataMap.put("field102", "1.7");
				dataMap.put("field259", "<=0.2mg/dL");
				dataMap.put("hfield102", "正常");
				dataMap.put("field237", "1.7");
				dataMap.put("field260", "<=0.2mg/dL");
				dataMap.put("hfield237", "正常");
				dataMap.put("field238", "1.7");
				dataMap.put("field261", "<=0.2mg/dL");
				dataMap.put("hfield238", "正常");
				dataMap.put("field104", "1.7");
				dataMap.put("field262", "<=0.2mg/dL");
				dataMap.put("hfield104", "正常");
				dataMap.put("field103", "1.7");
				dataMap.put("field263", "<=0.2mg/dL");
				dataMap.put("hfield103", "正常");
				dataMap.put("field239", "1.7");
				dataMap.put("field264", "<=0.2mg/dL");
				dataMap.put("hfield239", "正常");
				dataMap.put("field240", "1.7");
				dataMap.put("field265", "<=0.2mg/dL");
				dataMap.put("hfield240", "正常");
				dataMap.put("field241", "1.7");
				dataMap.put("field266", "<=0.2mg/dL");
				dataMap.put("hfield241", "正常");
				dataMap.put("field242", "1.7");
				dataMap.put("field267", "<=0.2mg/dL");
				dataMap.put("hfield242", "正常");
				dataMap.put("field117", "1.7");
				dataMap.put("hfield117", "正常");
				dataMap.put("field115", "1.7");
				dataMap.put("hfield115", "正常");
				dataMap.put("field114", "1.7");
				dataMap.put("hfield114", "正常");
				dataMap.put("field123", "1.7");
				dataMap.put("hfield123", "正常");
				dataMap.put("field124", "1.7");
				dataMap.put("hfield124", "正常");
				dataMap.put("field119", "1.7");
				dataMap.put("hfield119", "正常");
				dataMap.put("field120", "1.7");
				dataMap.put("hfield120", "正常");
				dataMap.put("field106", "1.7");
				dataMap.put("hfield106", "正常");
				dataMap.put("field125", "1.7");
				dataMap.put("hfield125", "正常");
				dataMap.put("field126", "1.7");
				dataMap.put("hfield126", "正常");
				dataMap.put("field14", "检察院");
				dataMap.put("field247", "检察院");
				dataMap.put("field248", "检察院");
				dataMap.put("ecgStr", "内容");
				dataMap.put("field249", "内容");
				dataMap.put("checkDate", "2018年04月25日");
				dataMap.put("field246", CreatePDFUtil.encodeBase64File(
						"http://iservice.oss-cn-beijing.aliyuncs.com/healthcare/bchao/2019/03/24/018782230622_00001.jpg",
						"D:/test.png"));
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/mreport2.pdf", "1.pdf", dataMap);
			} else if (num == 10) {// 个人基本信息
				dataMap.put("name", "测试");
				dataMap.put("code", "111111111111");
				dataMap.put("sex", "0");
				dataMap.put("birthdate", "2018年04月25日");
				dataMap.put("idcard", "111111111111");
				dataMap.put("company", "测试");
				dataMap.put("phoneno", "测试");
				dataMap.put("cname", "测试");
				dataMap.put("cphoneno", "测试");
				dataMap.put("rtype", "1");
				dataMap.put("nationality", "01");
				dataMap.put("blood", "1");
				dataMap.put("RH", "1");
				dataMap.put("elevel", "1");
				dataMap.put("career", "1");
				dataMap.put("marital", "1");
				dataMap.put("field1", "1111111111111");
				dataMap.put("field2", "1111111111111");
				dataMap.put("field3", "1111111111111");
				dataMap.put("paymentway1", "1");
				dataMap.put("paymentway2", "1");
				dataMap.put("paymentway3", "1");
				dataMap.put("field4", "啊啊啊啊");
				dataMap.put("allergy1", "1");
				dataMap.put("allergy2", "1");
				dataMap.put("allergy3", "1");
				dataMap.put("allergy4", "1");
				dataMap.put("exposure1", "1");
				dataMap.put("exposure2", "1");
				dataMap.put("exposure3", "1");
				dataMap.put("disease1", "1");
				dataMap.put("disease2", "1");
				dataMap.put("disease3", "1");
				dataMap.put("disease4", "1");
				dataMap.put("disease5", "1");
				dataMap.put("disease6", "1");
				dataMap.put("field10", "啊啊啊啊");
				dataMap.put("ctime1", "2010-10-10");
				dataMap.put("ctime2", "2010-10-10");
				dataMap.put("ctime3", "2010-10-10");
				dataMap.put("ctime4", "2010-10-10");
				dataMap.put("surgery", "1");
				dataMap.put("sname1", "啊啊啊啊啊");
				dataMap.put("stime1", "2010-10-10");
				dataMap.put("sname2", "啊啊啊啊啊");
				dataMap.put("stime2", "2010-10-10");
				dataMap.put("trauma", "1");
				dataMap.put("tname1", "啊啊啊啊啊");
				dataMap.put("ttime1", "2010-10-10");
				dataMap.put("tname2", "啊啊啊啊啊");
				dataMap.put("ttime2", "2010-10-10");
				dataMap.put("btran", "1");
				dataMap.put("breason1", "啊啊啊啊啊");
				dataMap.put("btime1", "2010-10-10");
				dataMap.put("breason2", "啊啊啊啊啊");
				dataMap.put("btime2", "2010-10-10");
				dataMap.put("father1", "1");
				dataMap.put("father2", "1");
				dataMap.put("father3", "1");
				dataMap.put("father4", "1");
				dataMap.put("father5", "1");
				dataMap.put("father6", "1");
				dataMap.put("mother1", "1");
				dataMap.put("mother2", "1");
				dataMap.put("mother3", "1");
				dataMap.put("mother4", "1");
				dataMap.put("mother5", "1");
				dataMap.put("mother6", "1");
				dataMap.put("bsrelative1", "1");
				dataMap.put("bsrelative2", "1");
				dataMap.put("bsrelative3", "1");
				dataMap.put("bsrelative4", "1");
				dataMap.put("bsrelative5", "1");
				dataMap.put("bsrelative6", "1");
				dataMap.put("children1", "1");
				dataMap.put("children2", "1");
				dataMap.put("children3", "1");
				dataMap.put("children4", "1");
				dataMap.put("children5", "1");
				dataMap.put("children6", "1");
				dataMap.put("genetic", "1");
				dataMap.put("dname", "啊啊");
				dataMap.put("disability1", "1");
				dataMap.put("disability2", "1");
				dataMap.put("disability3", "1");
				dataMap.put("disability4", "1");
				dataMap.put("disability5", "1");
				dataMap.put("disability6", "1");
				dataMap.put("field5", "啊啊啊");
				dataMap.put("field6", "111111111111111111");
				dataMap.put("field7", "2");
				dataMap.put("field8", "啊啊啊啊啊啊啊啊啊");
				dataMap.put("field9", "2");
				dataMap.put("kfacility", "2");
				dataMap.put("ftype", "2");
				dataMap.put("dwater", "2");
				dataMap.put("toilet", "2");
				dataMap.put("poultry", "2");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/personalBasic.pdf", "1.pdf", dataMap);
			} else if (num == 11) {// 健康体检
				dataMap.put("name", "测试");
				dataMap.put("code", "111111111111");
				dataMap.put("doctor", "王医生");
				dataMap.put("field2_1", "1");
				dataMap.put("field2_2", "1");
				dataMap.put("field2_3", "1");
				dataMap.put("field2_4", "1");
				dataMap.put("field2_5", "1");
				dataMap.put("field2_6", "1");
				dataMap.put("field2_7", "1");
				dataMap.put("field2_8", "1");
				dataMap.put("field2_9", "1");
				dataMap.put("field2_10", "1");
				dataMap.put("field1", "2018年04月25日");
				dataMap.put("field4", "1");
				dataMap.put("field5", "1");
				dataMap.put("field6", "1");
				dataMap.put("field7", "1");
				dataMap.put("field8", "1");
				dataMap.put("field9", "1");
				dataMap.put("field10", "1");
				dataMap.put("field11", "1");
				dataMap.put("field12", "1");
				dataMap.put("field13", "1");
				dataMap.put("field219", "1");
				dataMap.put("field15", "1");
				dataMap.put("field16", "1");
				dataMap.put("field17", "1");
				dataMap.put("field18", "1");
				dataMap.put("field19", "1");
				dataMap.put("field20", "1");
				dataMap.put("field21", "1");
				dataMap.put("field22", "1");
				dataMap.put("field23_1", "1");
				dataMap.put("field23_2", "1");
				dataMap.put("field23_3", "1");
				dataMap.put("field23_4", "1");
				dataMap.put("field23_5", "1");
				dataMap.put("field24", "1");
				dataMap.put("field25", "1");
				dataMap.put("field26", "1");
				dataMap.put("field27", "1");
				dataMap.put("field28", "1");
				dataMap.put("field29", "1");
				dataMap.put("field30", "1");
				dataMap.put("field31", "1");
				dataMap.put("field32", "1");
				dataMap.put("field33", "1");
				dataMap.put("field34_1", "1");
				dataMap.put("field34_2", "1");
				dataMap.put("field34_3", "1");
				dataMap.put("field34_4", "1");
				dataMap.put("field35", "1");
				dataMap.put("field36", "1");
				dataMap.put("field37", "1");
				dataMap.put("field38", "1");
				dataMap.put("field39", "1");
				dataMap.put("field40", "1");
				dataMap.put("field41", "1");
				dataMap.put("field42", "1");
				dataMap.put("field43", "1");
				dataMap.put("field44", "1");
				dataMap.put("field45", "1");
				dataMap.put("field46", "1");
				dataMap.put("field47", "1");
				dataMap.put("field48", "1");
				dataMap.put("field49", "1");
				dataMap.put("field50_1", "1");
				dataMap.put("field50_2", "1");
				dataMap.put("field50_3", "1");
				dataMap.put("field51", "1234567");
				dataMap.put("field52", "1234567");
				dataMap.put("field53", "1234567");
				dataMap.put("field54", "1234567");
				dataMap.put("field55", "1234567");
				dataMap.put("field56", "1234567");
				dataMap.put("field57", "1234567");
				dataMap.put("field58", "1234567");
				dataMap.put("field59", "1234567");
				dataMap.put("field60", "1234567");
				dataMap.put("field61", "1234567");
				dataMap.put("field62", "1234567");
				dataMap.put("field63", "1");
				dataMap.put("field64", "1");
				dataMap.put("field65", "1");
				dataMap.put("field66", "1");
				dataMap.put("field67", "1");
				dataMap.put("field68", "1");
				dataMap.put("field69", "1");
				dataMap.put("field70", "1");
				dataMap.put("field71", "1");
				dataMap.put("field72", "1");
				dataMap.put("field73", "1");
				dataMap.put("field74", "1");
				dataMap.put("field75", "1");
				dataMap.put("field76", "1");
				dataMap.put("field77", "1");
				dataMap.put("field78", "1");
				dataMap.put("field79", "1");
				dataMap.put("field80", "1");
				dataMap.put("field81", "1");
				dataMap.put("field82", "1");
				dataMap.put("field83", "1");
				dataMap.put("field84", "1");
				dataMap.put("field85", "1");
				dataMap.put("field86", "1");
				dataMap.put("field87", "1");
				dataMap.put("field88", "1");
				dataMap.put("field89", "1");
				dataMap.put("field90", "1");
				dataMap.put("field91", "1");
				dataMap.put("field92", "1");
				dataMap.put("field93", "1");
				dataMap.put("field94", "1");
				dataMap.put("field95", "1");
				dataMap.put("field96", "1");
				dataMap.put("field97", "1");
				dataMap.put("field98", "1");
				dataMap.put("field99", "1");
				dataMap.put("field100", "1");
				dataMap.put("field101", "1");
				dataMap.put("field102", "1");
				dataMap.put("field103", "1");
				dataMap.put("field104", "1");
				dataMap.put("field105", "1");
				dataMap.put("field106", "1");
				dataMap.put("field107", "1");
				dataMap.put("field108", "1");
				dataMap.put("field109", "1");
				dataMap.put("field110", "1");
				dataMap.put("field111", "1");
				dataMap.put("field112", "1");
				dataMap.put("field113", "1");
				dataMap.put("field114", "1");
				dataMap.put("field115", "1");
				dataMap.put("field116", "1");
				dataMap.put("field117", "1");
				dataMap.put("field118", "1");
				dataMap.put("field119", "1");
				dataMap.put("field120", "1");
				dataMap.put("field121", "1");
				dataMap.put("field122", "1");
				dataMap.put("field123", "1");
				dataMap.put("field124", "1");
				dataMap.put("field125", "1");
				dataMap.put("field126", "1");
				dataMap.put("field127_1", "1");
				dataMap.put("field127_2", "1");
				dataMap.put("field127_3", "1");
				dataMap.put("field127_4", "1");
				dataMap.put("field127_5", "1");
				dataMap.put("field127_6", "1");
				dataMap.put("field127_7", "1");
				dataMap.put("field127_8", "1");
				dataMap.put("field128", "1");
				dataMap.put("field129", "1");
				dataMap.put("field130", "1");
				dataMap.put("field131", "1");
				dataMap.put("field132", "1");
				dataMap.put("field133", "1");
				dataMap.put("field134", "1");
				dataMap.put("field135", "1");
				dataMap.put("field136", "1");
				dataMap.put("field137_1", "1");
				dataMap.put("field137_2", "1");
				dataMap.put("field137_3", "1");
				dataMap.put("field137_4", "1");
				dataMap.put("field137_5", "1");
				dataMap.put("field138", "1");
				dataMap.put("field139_1", "1");
				dataMap.put("field139_2", "1");
				dataMap.put("field139_3", "1");
				dataMap.put("field139_4", "1");
				dataMap.put("field139_5", "1");
				dataMap.put("field140", "1");
				dataMap.put("field141_1", "1");
				dataMap.put("field141_2", "1");
				dataMap.put("field141_3", "1");
				dataMap.put("field141_4", "1");
				dataMap.put("field141_5", "1");
				dataMap.put("field142", "1");
				dataMap.put("field143_1", "1");
				dataMap.put("field143_2", "1");
				dataMap.put("field143_3", "1");
				dataMap.put("field144", "1");
				dataMap.put("field145_1", "1");
				dataMap.put("field145_2", "1");
				dataMap.put("field145_3", "1");
				dataMap.put("field146", "1");
				dataMap.put("field147_1", "1");
				dataMap.put("field147_2", "1");
				dataMap.put("field147_3", "1");
				dataMap.put("field148", "1");
				dataMap.put("field149", "2019-01-01");
				dataMap.put("field150", "2019-01-01");
				dataMap.put("field151", "2019-01-01");
				dataMap.put("field152", "2019-01-01");
				dataMap.put("field153", "1");
				dataMap.put("field154", "1");
				dataMap.put("field155", "1");
				dataMap.put("field156", "1");
				dataMap.put("field157", "1");
				dataMap.put("field158", "1");
				dataMap.put("field159", "1");
				dataMap.put("field160", "1");
				dataMap.put("field161", "1");
				dataMap.put("field162", "1");
				dataMap.put("field163", "1");
				dataMap.put("field164", "1");
				dataMap.put("field165", "1");
				dataMap.put("field166", "1");
				dataMap.put("field167", "1");
				dataMap.put("field168", "1");
				dataMap.put("field169", "1");
				dataMap.put("field170", "1");
				dataMap.put("field171", "1");
				dataMap.put("field172", "1");
				dataMap.put("field173", "1");
				dataMap.put("field174", "1");
				dataMap.put("field175", "1");
				dataMap.put("field176", "1");
				dataMap.put("field177", "1");
				dataMap.put("field178", "1");
				dataMap.put("field179", "1");
				dataMap.put("field180", "1");
				dataMap.put("field181", "1");
				dataMap.put("field182", "1");
				dataMap.put("field183", "1");
				dataMap.put("field184", "1");
				dataMap.put("field185", "1");
				dataMap.put("field186", "1");
				dataMap.put("field187", "1");
				dataMap.put("field188", "1");
				dataMap.put("field189", "1");
				dataMap.put("field190", "1");
				dataMap.put("field191", "1");
				dataMap.put("field192", "1");
				dataMap.put("field193", "1");
				dataMap.put("field194", "1");
				dataMap.put("field195", "1");
				dataMap.put("field196", "1");
				dataMap.put("field197", "1");
				dataMap.put("field198", "1");
				dataMap.put("field199", "1");
				dataMap.put("field200", "1");
				dataMap.put("field201", "1");
				dataMap.put("field202", "1");
				dataMap.put("field203", "1");
				dataMap.put("field204", "1");
				dataMap.put("field205", "1");
				dataMap.put("field206", "1");
				dataMap.put("field207", "1");
				dataMap.put("field208", "1");
				dataMap.put("field209", "1");
				dataMap.put("field211", "1");
				dataMap.put("field212", "1");
				dataMap.put("field213", "1");
				dataMap.put("field214_1", "1");
				dataMap.put("field214_2", "1");
				dataMap.put("field214_3", "1");
				dataMap.put("field214_4", "1");
				dataMap.put("field215_1", "1");
				dataMap.put("field215_2", "1");
				dataMap.put("field215_3", "1");
				dataMap.put("field215_4", "1");
				dataMap.put("field215_5", "1");
				dataMap.put("field215_6", "1");
				dataMap.put("field215_7", "1");
				dataMap.put("field216", "1");
				dataMap.put("field217", "1");
				dataMap.put("field218", "1");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/healthCheckup.pdf", "1.pdf", dataMap);
			} else if (num == 12) {// 体检报告(A3)
				dataMap.put("name", "测试");
				dataMap.put("idcard", "111111111111");
				dataMap.put("phoneno", "111111111111");
				dataMap.put("address", "四川省江苏是啊啊啊啊啊啊啊");
				dataMap.put("code", "111111111111");
				dataMap.put("hname", "某某卫生院");
				dataMap.put("sex", "男");
				dataMap.put("age", "30");
				dataMap.put("field1", "2019年12月11日");
				dataMap.put("field11", "1");
				dataMap.put("field12", "1");
				dataMap.put("field219", "1");
				dataMap.put("hfield219", "正常");
				dataMap.put("field9", "1");
				dataMap.put("hfield9", "正常");
				dataMap.put("field10", "1");
				dataMap.put("hfield10", "正常");
				dataMap.put("field97", "1");
				dataMap.put("hfield97", "正常");
				dataMap.put("field98", "1");
				dataMap.put("hfield98", "正常");
				dataMap.put("field222", "1");
				dataMap.put("hfield222", "正常");
				dataMap.put("field223", "1");
				dataMap.put("hfield223", "正常");
				dataMap.put("field224", "1");
				dataMap.put("hfield224", "正常");
				dataMap.put("field225", "1");
				dataMap.put("hfield225", "正常");
				dataMap.put("field226", "1");
				dataMap.put("hfield226", "正常");
				dataMap.put("field227", "1");
				dataMap.put("hfield227", "正常");
				dataMap.put("field228", "1");
				dataMap.put("hfield228", "正常");
				dataMap.put("field229", "1");
				dataMap.put("hfield229", "正常");
				dataMap.put("field243", "1");
				dataMap.put("hfield243", "正常");
				dataMap.put("field230", "1");
				dataMap.put("hfield230", "正常");
				dataMap.put("field99", "1");
				dataMap.put("hfield99", "正常");
				dataMap.put("field231", "1");
				dataMap.put("hfield231", "正常");
				dataMap.put("field232", "1");
				dataMap.put("hfield232", "正常");
				dataMap.put("field233", "1");
				dataMap.put("hfield233", "正常");
				dataMap.put("field234", "1");
				dataMap.put("hfield234", "正常");
				dataMap.put("field235", "1");
				dataMap.put("hfield235", "正常");
				dataMap.put("field236", "1");
				dataMap.put("hfield236", "正常");
				dataMap.put("field14", "正常");
				dataMap.put("field101", "正常");
				dataMap.put("field258", "1");
				dataMap.put("hfield101", "正常");
				dataMap.put("field102", "1");
				dataMap.put("field259", "正常");
				dataMap.put("hfield102", "1");
				dataMap.put("field237", "正常");
				dataMap.put("field260", "1");
				dataMap.put("hfield237", "正常");
				dataMap.put("field238", "1");
				dataMap.put("field261", "正常");
				dataMap.put("hfield238", "1");
				dataMap.put("field104", "正常");
				dataMap.put("field262", "1");
				dataMap.put("hfield104", "正常");
				dataMap.put("field103", "1");
				dataMap.put("field263", "正常");
				dataMap.put("hfield103", "1");
				dataMap.put("field239", "正常");
				dataMap.put("field264", "1");
				dataMap.put("hfield239", "正常");
				dataMap.put("field240", "1");
				dataMap.put("field265", "正常");
				dataMap.put("hfield240", "1");
				dataMap.put("field241", "正常");
				dataMap.put("field266", "1");
				dataMap.put("hfield241", "正常");
				dataMap.put("field242", "1");
				dataMap.put("field267", "正常");
				dataMap.put("hfield242", "1");
				dataMap.put("field247", "正常");
				dataMap.put("field117", "1");
				dataMap.put("hfield117", "正常");
				dataMap.put("field115", "1");
				dataMap.put("hfield115", "正常");
				dataMap.put("field114", "1");
				dataMap.put("hfield114", "正常");
				dataMap.put("field123", "1");
				dataMap.put("hfield123", "正常");
				dataMap.put("field124", "1");
				dataMap.put("hfield124", "正常");
				dataMap.put("field119", "1");
				dataMap.put("hfield119", "正常");
				dataMap.put("field120", "1");
				dataMap.put("hfield120", "正常");
				dataMap.put("field106", "1");
				dataMap.put("hfield106", "正常");
				dataMap.put("field125", "1");
				dataMap.put("hfield125", "正常");
				dataMap.put("field126", "1");
				dataMap.put("hfield126", "正常");
				dataMap.put("field248", "正常");
				dataMap.put("field246", CreatePDFUtil.encodeBase64File(
						"http://iservice.oss-cn-beijing.aliyuncs.com/healthcare/bchao/2019/03/24/018782230622_00001.jpg",
						"D:/test.png"));
				dataMap.put("ecgStr", "正常");
				dataMap.put("field249", "正常");
				dataMap.put("field210", CreatePDFUtil.encodeBase64File(
						"http://iservice.oss-cn-beijing.aliyuncs.com/healthcare/bchao/2019/03/24/018782230622_00001.jpg",
						"D:/test.png"));
				dataMap.put("field244", "正常");
				dataMap.put("field245", "正常");
				dataMap.put("field250", "正常");
				dataMap.put("resultLab", "正常");
				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/mreportA3.pdf", "1.pdf", dataMap);
			} else if (num == 13) {// 存档报告
				dataMap.put("num1", "1");
				dataMap.put("num2", "2");
				dataMap.put("num3", "3");
				dataMap.put("num4", "4");
				dataMap.put("num5", "5");
				dataMap.put("num6", "6");
				dataMap.put("num7", "7");
				dataMap.put("num8", "8");
				dataMap.put("num9", "9");
				dataMap.put("num10", "0");
				dataMap.put("num11", "1");
				dataMap.put("num12", "2");
				dataMap.put("name", "粟寿伟");
				dataMap.put("address", "四川省开江县普安镇九石坎村２组６５号");
				dataMap.put("address1", "四川省开江县普安镇九石坎村２组６５号");
				dataMap.put("phoneno", "18982811362");
				dataMap.put("countyname", "普安镇");
				dataMap.put("vcname", "九石坎");
				dataMap.put("fileunit", "开江县普安镇卫生院");
				dataMap.put("fileuser", "吴法政");
				dataMap.put("doctor", "吴法政");
				dataMap.put("filedate", "2018年04月25日");

				dataMap.put("code", "111111111111");
				dataMap.put("doctor", "王医生");
				dataMap.put("field2_1", "1");
				dataMap.put("field2_2", "1");
				dataMap.put("field2_3", "1");
				dataMap.put("field2_4", "1");
				dataMap.put("field2_5", "1");
				dataMap.put("field2_6", "1");
				dataMap.put("field2_7", "1");
				dataMap.put("field2_8", "1");
				dataMap.put("field2_9", "1");
				dataMap.put("field2_10", "1");
				dataMap.put("field1", "2018年04月25日");
				dataMap.put("field4", "1");
				dataMap.put("field5", "1");
				dataMap.put("field6", "1");
				dataMap.put("field7", "1");
				dataMap.put("field8", "1");
				dataMap.put("field9", "1");
				dataMap.put("field10", "1");
				dataMap.put("field11", "1");
				dataMap.put("field12", "1");
				dataMap.put("field13", "1");
				dataMap.put("field219", "1");
				dataMap.put("field15", "1");
				dataMap.put("field16", "1");
				dataMap.put("field17", "1");
				dataMap.put("field18", "1");
				dataMap.put("field19", "1");
				dataMap.put("field20", "1");
				dataMap.put("field21", "1");
				dataMap.put("field22", "1");
				dataMap.put("field23_1", "1");
				dataMap.put("field23_2", "1");
				dataMap.put("field23_3", "1");
				dataMap.put("field23_4", "1");
				dataMap.put("field23_5", "1");
				dataMap.put("field24", "1");
				dataMap.put("field25", "1");
				dataMap.put("field26", "1");
				dataMap.put("field27", "1");
				dataMap.put("field28", "1");
				dataMap.put("field29", "1");
				dataMap.put("field30", "1");
				dataMap.put("field31", "1");
				dataMap.put("field32", "1");
				dataMap.put("field33", "1");
				dataMap.put("field34_1", "1");
				dataMap.put("field34_2", "1");
				dataMap.put("field34_3", "1");
				dataMap.put("field34_4", "1");
				dataMap.put("field35", "1");
				dataMap.put("field36", "1");
				dataMap.put("field37", "1");
				dataMap.put("field38", "1");
				dataMap.put("field39", "1");
				dataMap.put("field40", "1");
				dataMap.put("field41", "1");
				dataMap.put("field42", "1");
				dataMap.put("field43", "1");
				dataMap.put("field44", "1");
				dataMap.put("field45", "1");
				dataMap.put("field46", "1");
				dataMap.put("field47", "1");
				dataMap.put("field48", "1");
				dataMap.put("field49", "1");
				dataMap.put("field50_1", "1");
				dataMap.put("field50_2", "1");
				dataMap.put("field50_3", "1");
				dataMap.put("field51", "1");
				dataMap.put("field52", "1");
				dataMap.put("field53", "1");
				dataMap.put("field54", "1");
				dataMap.put("field55", "1");
				dataMap.put("field56", "1");
				dataMap.put("field57", "1");
				dataMap.put("field58", "1");
				dataMap.put("field59", "1");
				dataMap.put("field60", "1");
				dataMap.put("field61", "1");
				dataMap.put("field62", "1");
				dataMap.put("field63", "1");
				dataMap.put("field64", "1");
				dataMap.put("field65", "1");
				dataMap.put("field66", "1");
				dataMap.put("field67", "1");
				dataMap.put("field68", "1");
				dataMap.put("field69", "1");
				dataMap.put("field70", "1");
				dataMap.put("field71", "1");
				dataMap.put("field72", "1");
				dataMap.put("field73", "1");
				dataMap.put("field74", "1");
				dataMap.put("field75", "1");
				dataMap.put("field76", "1");
				dataMap.put("field77", "1");
				dataMap.put("field78", "1");
				dataMap.put("field79", "1");
				dataMap.put("field80", "1");
				dataMap.put("field81", "1");
				dataMap.put("field82", "1");
				dataMap.put("field83", "1");
				dataMap.put("field84", "1");
				dataMap.put("field85", "1");
				dataMap.put("field86", "1");
				dataMap.put("field87", "1");
				dataMap.put("field88", "1");
				dataMap.put("field89", "1");
				dataMap.put("field90", "1");
				dataMap.put("field91", "1");
				dataMap.put("field92", "1");
				dataMap.put("field93", "1");
				dataMap.put("field94", "1");
				dataMap.put("field95", "1");
				dataMap.put("field96", "1");
				dataMap.put("field97", "1");
				dataMap.put("field98", "1");
				dataMap.put("field99", "1");
				dataMap.put("field100", "1");
				dataMap.put("field101", "1");
				dataMap.put("field102", "1");
				dataMap.put("field103", "1");
				dataMap.put("field104", "1");
				dataMap.put("field105", "1");
				dataMap.put("field106", "1");
				dataMap.put("field107", "1");
				dataMap.put("field108", "1");
				dataMap.put("field109", "1");
				dataMap.put("field110", "1");
				dataMap.put("field111", "1");
				dataMap.put("field112", "1");
				dataMap.put("field113", "1");
				dataMap.put("field114", "1");
				dataMap.put("field115", "1");
				dataMap.put("field116", "1");
				dataMap.put("field117", "1");
				dataMap.put("field118", "1");
				dataMap.put("field119", "1");
				dataMap.put("field120", "1");
				dataMap.put("field121", "1");
				dataMap.put("field122", "1");
				dataMap.put("field123", "1");
				dataMap.put("field124", "1");
				dataMap.put("field125", "1");
				dataMap.put("field126", "1");
				dataMap.put("field127_1", "1");
				dataMap.put("field127_2", "1");
				dataMap.put("field127_3", "1");
				dataMap.put("field127_4", "1");
				dataMap.put("field127_5", "1");
				dataMap.put("field127_6", "1");
				dataMap.put("field127_7", "1");
				dataMap.put("field127_8", "1");
				dataMap.put("field128", "1");
				dataMap.put("field129", "1");
				dataMap.put("field130", "1");
				dataMap.put("field131", "1");
				dataMap.put("field132", "1");
				dataMap.put("field133", "1");
				dataMap.put("field134", "1");
				dataMap.put("field135", "1");
				dataMap.put("field136", "1");
				dataMap.put("field137_1", "1");
				dataMap.put("field137_2", "1");
				dataMap.put("field137_3", "1");
				dataMap.put("field137_4", "1");
				dataMap.put("field137_5", "1");
				dataMap.put("field138", "1");
				dataMap.put("field139_1", "1");
				dataMap.put("field139_2", "1");
				dataMap.put("field139_3", "1");
				dataMap.put("field139_4", "1");
				dataMap.put("field139_5", "1");
				dataMap.put("field140", "1");
				dataMap.put("field141_1", "1");
				dataMap.put("field141_2", "1");
				dataMap.put("field141_3", "1");
				dataMap.put("field141_4", "1");
				dataMap.put("field141_5", "1");
				dataMap.put("field142", "1");
				dataMap.put("field143_1", "1");
				dataMap.put("field143_2", "1");
				dataMap.put("field143_3", "1");
				dataMap.put("field144", "1");
				dataMap.put("field145_1", "1");
				dataMap.put("field145_2", "1");
				dataMap.put("field145_3", "1");
				dataMap.put("field146", "1");
				dataMap.put("field147_1", "1");
				dataMap.put("field147_2", "1");
				dataMap.put("field147_3", "1");
				dataMap.put("field148", "1");
				dataMap.put("field149", "2019-01-01");
				dataMap.put("field150", "2019-01-01");
				dataMap.put("field151", "2019-01-01");
				dataMap.put("field152", "2019-01-01");
				dataMap.put("field153", "1");
				dataMap.put("field154", "1");
				dataMap.put("field155", "1");
				dataMap.put("field156", "1");
				dataMap.put("field157", "1");
				dataMap.put("field158", "1");
				dataMap.put("field159", "1");
				dataMap.put("field160", "1");
				dataMap.put("field161", "1");
				dataMap.put("field162", "1");
				dataMap.put("field163", "1");
				dataMap.put("field164", "1");
				dataMap.put("field165", "1");
				dataMap.put("field166", "1");
				dataMap.put("field167", "1");
				dataMap.put("field168", "1");
				dataMap.put("field169", "1");
				dataMap.put("field170", "1");
				dataMap.put("field171", "1");
				dataMap.put("field172", "1");
				dataMap.put("field173", "1");
				dataMap.put("field174", "1");
				dataMap.put("field175", "1");
				dataMap.put("field176", "1");
				dataMap.put("field177", "1");
				dataMap.put("field178", "1");
				dataMap.put("field179", "1");
				dataMap.put("field180", "1");
				dataMap.put("field181", "1");
				dataMap.put("field182", "1");
				dataMap.put("field183", "1");
				dataMap.put("field184", "1");
				dataMap.put("field185", "1");
				dataMap.put("field186", "1");
				dataMap.put("field187", "1");
				dataMap.put("field188", "1");
				dataMap.put("field189", "1");
				dataMap.put("field190", "1");
				dataMap.put("field191", "1");
				dataMap.put("field192", "1");
				dataMap.put("field193", "1");
				dataMap.put("field194", "1");
				dataMap.put("field195", "1");
				dataMap.put("field196", "1");
				dataMap.put("field197", "1");
				dataMap.put("field198", "1");
				dataMap.put("field199", "1");
				dataMap.put("field200", "1");
				dataMap.put("field201", "1");
				dataMap.put("field202", "1");
				dataMap.put("field203", "1");
				dataMap.put("field204", "1");
				dataMap.put("field205", "1");
				dataMap.put("field206", "1");
				dataMap.put("field207", "1");
				dataMap.put("field208", "1");
				dataMap.put("field209", "1");
				dataMap.put("field211", "1");
				dataMap.put("field212", "1");
				dataMap.put("field213", "1");
				dataMap.put("field214_1", "1");
				dataMap.put("field214_2", "1");
				dataMap.put("field214_3", "1");
				dataMap.put("field214_4", "1");
				dataMap.put("field215_1", "1");
				dataMap.put("field215_2", "1");
				dataMap.put("field215_3", "1");
				dataMap.put("field215_4", "1");
				dataMap.put("field215_5", "1");
				dataMap.put("field215_6", "1");
				dataMap.put("field215_7", "1");
				dataMap.put("field216", "1");
				dataMap.put("field217", "1");
				dataMap.put("field218", "1");

				dataMap.put("tfield1", "2");
				dataMap.put("tfield2", "2");
				dataMap.put("tfield3", "2");
				dataMap.put("tfield4", "2");
				dataMap.put("tfield5", "2");
				dataMap.put("tfield6", "2");
				dataMap.put("tfield7", "2");
				dataMap.put("tfield8", "2");
				dataMap.put("tfield9", "2");
				dataMap.put("tfield10", "2");
				dataMap.put("tfield11", "2");
				dataMap.put("tfield12", "2");
				dataMap.put("tfield13", "2");
				dataMap.put("tfield14", "2");
				dataMap.put("tfield15", "2");
				dataMap.put("tfield16", "2");
				dataMap.put("tfield17", "2");
				dataMap.put("tfield18", "2");
				dataMap.put("tfield19", "2");
				dataMap.put("tfield20", "2");
				dataMap.put("tfield21", "2");
				dataMap.put("tfield22", "2");
				dataMap.put("tfield23", "2");
				dataMap.put("tfield24", "2");
				dataMap.put("tfield25", "2");
				dataMap.put("tfield26", "2");
				dataMap.put("tfield27", "2");
				dataMap.put("tfield28", "2");
				dataMap.put("tfield29", "2");
				dataMap.put("tfield30", "2");
				dataMap.put("tfield31", "2");
				dataMap.put("tfield32", "2");
				dataMap.put("tfield33", "2");
				dataMap.put("tfield34", "2");
				dataMap.put("tfield343", "√");
				dataMap.put("tfield344", "√");
				dataMap.put("tfield345", "√");
				dataMap.put("tfield346", "√");
				dataMap.put("tfield347", "√");
				dataMap.put("tfield35", "2");
				dataMap.put("tfield353", "√");
				dataMap.put("tfield354", "√");
				dataMap.put("tfield355", "√");
				dataMap.put("tfield356", "√");
				dataMap.put("tfield357", "√");
				dataMap.put("tfield36", "2");
				dataMap.put("tfield363", "√");
				dataMap.put("tfield364", "√");
				dataMap.put("tfield365", "√");
				dataMap.put("tfield366", "√");
				dataMap.put("tfield367", "√");
				dataMap.put("tfield37", "2");
				dataMap.put("tfield373", "√");
				dataMap.put("tfield374", "√");
				dataMap.put("tfield375", "√");
				dataMap.put("tfield376", "√");
				dataMap.put("tfield377", "√");
				dataMap.put("tfield38", "2");
				dataMap.put("tfield383", "√");
				dataMap.put("tfield384", "√");
				dataMap.put("tfield385", "√");
				dataMap.put("tfield386", "√");
				dataMap.put("tfield387", "√");
				dataMap.put("tfield39", "2");
				dataMap.put("tfield393", "√");
				dataMap.put("tfield394", "√");
				dataMap.put("tfield395", "√");
				dataMap.put("tfield396", "√");
				dataMap.put("tfield397", "√");
				dataMap.put("tfield40", "2");
				dataMap.put("tfield403", "√");
				dataMap.put("tfield404", "√");
				dataMap.put("tfield405", "√");
				dataMap.put("tfield406", "√");
				dataMap.put("tfield407", "√");
				dataMap.put("tfield41", "2");
				dataMap.put("tfield413", "√");
				dataMap.put("tfield414", "√");
				dataMap.put("tfield415", "√");
				dataMap.put("tfield416", "√");
				dataMap.put("tfield417", "√");
				dataMap.put("tfield42", "2");
				dataMap.put("tfield423", "√");
				dataMap.put("tfield424", "√");
				dataMap.put("tfield425", "√");
				dataMap.put("tfield426", "√");
				dataMap.put("tfield427", "√");
				// 气虚质得分
				dataMap.put("tfield53", "21");
				// 阳虚质得分
				dataMap.put("tfield54", "21");
				// 阴虚质得分
				dataMap.put("tfield55", "21");
				// 痰湿质得分
				dataMap.put("tfield56", "21");
				// 湿热质得分
				dataMap.put("tfield57", "21");
				// 血瘀质得分
				dataMap.put("tfield58", "21");
				// 气郁质得分
				dataMap.put("tfield59", "21");
				// 特禀质得分
				dataMap.put("tfield60", "21");
				// 平和质得分
				dataMap.put("tfield61", "21");

				dataMap.put("s1", "1");
				dataMap.put("s2", "2");
				dataMap.put("s3", "3");
				dataMap.put("s4", "4");
				dataMap.put("s5", "5");
				dataMap.put("total", "10");
				dataMap.put("sfield7", "目标");
				dataMap.put("sfield8", "2019年12月11日");

				CreatePDFUtil.newPdf("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/",
						"D:/eclipse-workspace/HealthCare/src/main/webapp/template/archive.pdf", "1.pdf", dataMap);
			} else if (num == 14) {// 西充县家庭医生签约
				dataMap.put("field1", "测试");
				dataMap.put("field2", "啊啊啊");
				dataMap.put("field3", "男");
				dataMap.put("birthday", "2010-10-10");
				dataMap.put("address", "啊啊鞍山市撒11号啊啊鞍山市撒11号");
				dataMap.put("dno", "19221122222");
				dataMap.put("field4", "19221122222");
				dataMap.put("field5", "张三三");
				dataMap.put("field6", "啊啊鞍山市撒11号");
				dataMap.put("field7", "11111111111");
				dataMap.put("field8", "张三三");
				dataMap.put("field9", "啊啊鞍山市撒11号");
				dataMap.put("field10", "11111111111");
				dataMap.put("field11", "张三三");
				dataMap.put("field12", "啊啊鞍山市撒11号");
				dataMap.put("field13", "11111111111");
				dataMap.put("field14", "张三三");
				dataMap.put("field15", "啊啊鞍山市撒11号");
				dataMap.put("field16", "11111111111");
				dataMap.put("field17", "张三三");
				dataMap.put("field18", "啊啊鞍山市撒11号");
				dataMap.put("field19", "11111111111");
				dataMap.put("field20", "张三三");
				dataMap.put("field21", "啊啊鞍山市撒11号");
				dataMap.put("field22", "11111111111");
				dataMap.put("field23", "张三三");
				dataMap.put("field24", "啊啊鞍山市撒11号");
				dataMap.put("field25", "11111111111");
				dataMap.put("field26", "啊啊鞍山市撒11号");
				dataMap.put("field27", "11111111111");
				dataMap.put("field28", "✓");
				dataMap.put("field29", "✓");
				dataMap.put("field30", "✓");
				dataMap.put("field31", "✓");
				dataMap.put("field32", "✓");
				dataMap.put("field33", "✓");
				dataMap.put("field34", "✓");
				dataMap.put("field35", "✓");
				dataMap.put("field36", "✓");
				dataMap.put("field37", "啊啊测试测试服务类型");
				dataMap.put("field38", "140");
				dataMap.put("field39", "体检人");
				dataMap.put("field40", "卫生院");
				dataMap.put("field41", "2020");
				dataMap.put("field42", "10");
				dataMap.put("field43", "21");
				dataMap.put("field44", "2020");
				dataMap.put("field45", "10");
				dataMap.put("field46", "21");
				CreatePDFUtil.newPdf("/Users/jeff/work/itearoa/HealthCare/NewCode/HealthCare/src/main/webapp/printTemplate/",
						"/Users/jeff/work/itearoa/HealthCare/NewCode/HealthCare/src/main/webapp/template/doctor.pdf", "doctor.pdf", dataMap);
			}else if (num == 15) {// 合并pdf
				List<String> files = new ArrayList<String>();
				files.add("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/20190409/a.pdf");
				files.add("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/20190409/b.pdf");
				CreatePDFUtil.PDFMerger("D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/", files,
						"D:/eclipse-workspace/HealthCare/src/main/webapp/printTemplate/1.pdf");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
