--
-- Database: `HealthCare`
--

-- --------------------------------------------------------
-- 删除表结构
DROP TABLE IF EXISTS `hislog`;
DROP TABLE IF EXISTS `healthcheckup`;
DROP TABLE IF EXISTS `selfcare`;
DROP TABLE IF EXISTS `TCM`;
DROP TABLE IF EXISTS `patients`;
DROP TABLE IF EXISTS `doctorsign`;
DROP TABLE IF EXISTS `users`;
DROP TABLE IF EXISTS `healthcenters`;
DROP TABLE IF EXISTS `areas`;
DROP TABLE IF EXISTS `ECG`;

CREATE TABLE `areas` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(50) NOT NULL UNIQUE COMMENT '区域代码',
  `name` varchar(50) NOT NULL COMMENT '区域名称',
  `pname` varchar(50) NOT NULL COMMENT '全区域名称',
  `pcode` varchar(50) NULL DEFAULT NULL COMMENT '上级区域代码',
  `hcode` varchar(50) NULL DEFAULT NULL COMMENT '接口区域代码',
  `level` int(1) NOT NULL COMMENT '层级',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  CONSTRAINT `areas_pcode` FOREIGN KEY (`pcode`) REFERENCES `areas` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='区域表';

CREATE TABLE `healthcenters` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(20) NOT NULL COMMENT '名称',
  `productcode` varchar(50) DEFAULT NULL COMMENT '产品代码',
  `orgid` varchar(50) DEFAULT NULL COMMENT '机构代码',
  `province` varchar(50) NULL DEFAULT NULL COMMENT '省份代码',
  `city` varchar(50) NULL DEFAULT NULL COMMENT '城市代码',
  `district` varchar(50) NULL DEFAULT NULL COMMENT '区/县代码',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  CONSTRAINT `areas_province` FOREIGN KEY (`province`) REFERENCES `areas` (`code`),
  CONSTRAINT `areas_city` FOREIGN KEY (`city`) REFERENCES `areas` (`code`),
  CONSTRAINT `areas_district` FOREIGN KEY (`district`) REFERENCES `areas` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='卫生所表';

CREATE TABLE `patients` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(20) NOT NULL COMMENT '档案编号',
  `name` varchar(20) DEFAULT NULL COMMENT '姓名',
  `address` varchar(100) DEFAULT NULL COMMENT '现住址',
  `address1` varchar(100) DEFAULT NULL COMMENT '户籍地址',
  `countyname` varchar(100) DEFAULT NULL COMMENT '乡镇(街道)名称',
  `vcname` varchar(100) DEFAULT NULL COMMENT '村(居)委会名称',
  `fileunit` varchar(100) DEFAULT NULL COMMENT '建档单位',
  `fileuser` varchar(100) DEFAULT NULL COMMENT '建档人',
  `doctor` varchar(100) DEFAULT NULL COMMENT '责任医生',
  `sex` int(1) DEFAULT NULL COMMENT '性别(1男2女3未说明的性别4未知的性别)',
  `birthdate` date DEFAULT NULL COMMENT '出生日期',
  `idcard` varchar(20) DEFAULT NULL COMMENT '身份证',
  `idimg` varchar(300) DEFAULT NULL COMMENT '身份证图片',
  `company` varchar(100) DEFAULT NULL COMMENT '工作单位',
  `phoneno` varchar(20) DEFAULT NULL COMMENT '本人电话',
  `cname` varchar(50) DEFAULT NULL COMMENT '联系人姓名',
  `cphoneno` varchar(20) DEFAULT NULL COMMENT '联系人电话',
  `rtype` int(1) DEFAULT NULL COMMENT '常驻类型(1户籍2非户籍)',
  `nationality` varchar(100) DEFAULT NULL COMMENT '民族',
  `blood` int(1) DEFAULT NULL COMMENT '血型1A型2B型3O型4AB型5不详',
  `RH` int(1) DEFAULT NULL COMMENT 'RH1阴性2阳性3不详',
  `elevel` int(2) DEFAULT NULL COMMENT '文化程度1研究生2大学本科3大学专科和专科学校4中等专业学校5技工学校6高中7初中8小学9文盲或半文盲10不详',
  `career` int(1) DEFAULT NULL COMMENT '职业1国家机关、党群组织、企业、事业单位负责人2专业技术人员3办事人员和有关人员4商业、服务业人员5农、林、牧、渔、水利业生产人员6生产、运输设备操作人员及有关人员7军人8不便分类的其他从业人员9无职业',
  `marital` int(1) DEFAULT NULL COMMENT '婚姻状况1未婚2已婚3丧偶4离婚5未说明的婚姻状况',
  `paymentway` varchar(20) DEFAULT NULL COMMENT '医疗费用支付方式1城镇职工基本医疗保险2城镇居民基本医疗保险3新型农村合作医疗4贫困救助5商业医疗保险6全公费7全自费8其他',
  `allergy` varchar(20) DEFAULT NULL COMMENT '药物过敏史1无2青霉素3磺胺4链霉素5其他',
  `exposure` varchar(20) DEFAULT NULL COMMENT '暴露史1无2化学品3毒物4射线',
  `disease` varchar(100) DEFAULT NULL COMMENT '疾病1无2高血压3糖料病4冠心病5慢性阻塞性肺疾病6恶性肿瘤7脑卒中8严重精神障碍9结核病10肝炎11其他法定传染病12职业病13其他',
  `ctime1` timestamp NULL DEFAULT NULL COMMENT '确诊时间1',
  `ctime2` timestamp NULL DEFAULT NULL COMMENT '确诊时间2',
  `ctime3` timestamp NULL DEFAULT NULL COMMENT '确诊时间3',
  `ctime4` timestamp NULL DEFAULT NULL COMMENT '确诊时间4',
  `surgery` int(1) DEFAULT NULL COMMENT '手术1无2有',
  `sname1` varchar(100) DEFAULT NULL COMMENT '手术名称1',
  `stime1` timestamp NULL DEFAULT NULL COMMENT '手术时间1',
  `sname2` varchar(100) DEFAULT NULL COMMENT '手术名称2',
  `stime2` timestamp NULL DEFAULT NULL COMMENT '手术时间2',
  `trauma` int(1) DEFAULT NULL COMMENT '外伤1无2有',
  `tname1` varchar(100) DEFAULT NULL COMMENT '外伤名称1',
  `ttime1` timestamp NULL DEFAULT NULL COMMENT '外伤时间1',
  `tname2` varchar(100) DEFAULT NULL COMMENT '外伤名称2',
  `ttime2` timestamp NULL DEFAULT NULL COMMENT '外伤时间2',
  `btran` int(1) DEFAULT NULL COMMENT '输血1无2有',
  `breason1` varchar(100) DEFAULT NULL COMMENT '输血原因1',
  `btime1` timestamp NULL DEFAULT NULL COMMENT '输血时间1',
  `breason2` varchar(100) DEFAULT NULL COMMENT '输血原因2',
  `btime2` timestamp NULL DEFAULT NULL COMMENT '输血时间2',
  `father` varchar(20) DEFAULT NULL COMMENT '父亲1无2高血压3糖尿病4冠心病5慢性阻塞性肺疾病6恶性肿瘤7脑卒中8严重精神障碍9结核病10肝炎11先天畸形12其他',
  `mother` varchar(20) DEFAULT NULL COMMENT '母亲',
  `bsrelative` varchar(20) DEFAULT NULL COMMENT '兄弟姐妹',
  `children` varchar(20) DEFAULT NULL COMMENT '子女',
  `genetic` int(1) DEFAULT NULL COMMENT '遗传病史1无2有',
  `dname` varchar(100) DEFAULT NULL COMMENT '疾病名称',
  `disability` varchar(20) DEFAULT NULL COMMENT '残疾情况1无残疾2视力残疾3听力残疾4语言残疾5肢体残疾6智力残疾7精神残疾8其他残疾',
  `kfacility` int(1) DEFAULT NULL COMMENT '厨房排风设施1无2油烟机3换气扇4烟囱',
  `ftype` int(1) DEFAULT NULL COMMENT '燃料类型1液化气2煤3天然气4沼气5柴火6其他',
  `dwater` int(1) DEFAULT NULL COMMENT '饮水1自来水2经净化过滤的水3井水4河湖水5塘水6其他',
  `toilet` int(1) DEFAULT NULL COMMENT '厕所1卫生厕所2一格或二格粪池式3马桶4露天粪坑5简易棚厕',
  `poultry` int(1) DEFAULT NULL COMMENT '禽畜栏1无2单设3室内4室外',
  `hcid` int(11) DEFAULT NULL COMMENT '卫生所',
  `field1` varchar(50) DEFAULT NULL COMMENT '医保卡号(城镇保险)',
  `field2` varchar(50) DEFAULT NULL COMMENT '医保卡号(居民基本保险)',
  `field3` varchar(50) DEFAULT NULL COMMENT '卡号',
  `field4` varchar(100) DEFAULT NULL COMMENT '医疗费用支付方式其他',
  `field5` varchar(20) DEFAULT NULL COMMENT '户主姓名',
  `field6` varchar(50) DEFAULT NULL COMMENT '户主身份证',
  `field7` varchar(10) DEFAULT NULL COMMENT '家庭人口数',
  `field8` varchar(100) DEFAULT NULL COMMENT '家庭结构',
  `field9` int(1) DEFAULT NULL COMMENT '居住情况1与成年子女同住2与子孙三代(四代)同住3夫妻二人同住4独居5计划生育特殊家庭',
  `field10` varchar(100) DEFAULT NULL COMMENT '疾病其他',
  `filedate` timestamp NULL DEFAULT NULL COMMENT '建档日期',
  `mtid` varchar(50) DEFAULT NULL COMMENT '体检主表ID',
  `personid` varchar(50) DEFAULT NULL COMMENT '居民ID',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  UNIQUE KEY `code` (`code`),
  KEY `heals_patients_FK` (`hcid`),
  CONSTRAINT `heals_patients_FK` FOREIGN KEY (`hcid`) REFERENCES `healthcenters` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='病人表';

CREATE TABLE `ecg` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `url` varchar(300) NOT NULL COMMENT 'url路径',
  `isread` int(11) DEFAULT '0' COMMENT '0未读1已读',
  `status` int(11) DEFAULT '0' COMMENT '0心电1生化',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='excel存放表';

CREATE TABLE `healthcheckup` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `field1` timestamp NULL DEFAULT NULL COMMENT '体检日期',
  `field2` varchar(100) DEFAULT NULL COMMENT '症状1无症状2头痛3头晕4心悸5胸闷6胸痛7慢性咳嗽8咳痰9呼吸困难10多饮11多尿12体重下降13乏力14关节肿痛15视力模糊16手脚麻木17尿急18尿痛19便秘20腹泻21恶心呕吐22眼花23耳鸣24乳房胀痛25其他',
  `field3` varchar(100) DEFAULT NULL COMMENT '症状其他',
  `field4` varchar(20) DEFAULT NULL COMMENT '体温',
  `field5` varchar(20) DEFAULT NULL COMMENT '脉率',
  `field6` varchar(20) DEFAULT NULL COMMENT '呼吸频率',
  `field7` varchar(20) DEFAULT NULL COMMENT '血压左侧1',
  `field8` varchar(20) DEFAULT NULL COMMENT '血压左侧2',
  `field9` varchar(20) DEFAULT NULL COMMENT '血压右侧1',
  `field10` varchar(20) DEFAULT NULL COMMENT '血压右侧2',
  `field11` varchar(20) DEFAULT NULL COMMENT '身高',
  `field12` varchar(20) DEFAULT NULL COMMENT '体重',
  `field13` varchar(20) DEFAULT NULL COMMENT '腰围',
  `field14` varchar(20) DEFAULT NULL COMMENT '血常规检查员',
  `field15` int(1) DEFAULT NULL COMMENT '老年人健康状态评估1满意2基本满意3说不清楚4不太满意5不满意',
  `field16` int(1) DEFAULT NULL COMMENT '老年人自理能力评估1可自理2轻度依赖3中度依赖4不能自理',
  `field17` int(1) DEFAULT NULL COMMENT '老年人认知功能1粗筛阴性2粗筛阳性',
  `field18` int(1) DEFAULT NULL COMMENT '老年人情感状态1粗筛阴性2粗筛阳性',
  `field19` int(1) DEFAULT NULL COMMENT '锻炼频率1每天2每周一次以上3偶尔4不锻炼',
  `field20` varchar(50) DEFAULT NULL COMMENT '每次锻炼时间',
  `field21` varchar(50) DEFAULT NULL COMMENT '坚持锻炼时间',
  `field22` varchar(50) DEFAULT NULL COMMENT '锻炼方式',
  `field23` varchar(20) DEFAULT NULL COMMENT '饮食习惯1荤素均衡2荤食为主3素食为主4嗜盐5嗜油6嗜糖',
  `field24` int(1) DEFAULT NULL COMMENT '吸烟状况1从不吸烟2已戒烟3吸烟',
  `field25` varchar(50) DEFAULT NULL COMMENT '日吸烟量',
  `field26` varchar(50) DEFAULT NULL COMMENT '开始吸烟年龄',
  `field27` varchar(50) DEFAULT NULL COMMENT '戒烟年龄',
  `field28` int(1) DEFAULT NULL COMMENT '饮酒频率1从不2偶尔3经常4每天',
  `field29` varchar(50) DEFAULT NULL COMMENT '日饮酒量',
  `field30` int(1) DEFAULT NULL COMMENT '是否戒酒1未戒酒2已戒酒',
  `field31` varchar(50) DEFAULT NULL COMMENT '戒酒年龄',
  `field32` varchar(50) DEFAULT NULL COMMENT '开始饮酒年龄',
  `field33` int(1) DEFAULT NULL COMMENT '近一年内是否曾醉酒1是2否',
  `field34` varchar(20) DEFAULT NULL COMMENT '饮酒种类1白酒2啤酒3红酒4黄酒5其他',
  `field35` varchar(50) DEFAULT NULL COMMENT '饮酒种类其他',
  `field36` int(1) DEFAULT NULL COMMENT '职业病危害1无2有',
  `field37` varchar(50) DEFAULT NULL COMMENT '工种',
  `field38` varchar(50) DEFAULT NULL COMMENT '年限',
  `field39` varchar(50) DEFAULT NULL COMMENT '粉尘',
  `field40` int(1) DEFAULT NULL COMMENT '粉尘防护措施1有2无',
  `field41` varchar(50) DEFAULT NULL COMMENT '放射物质',
  `field42` int(1) DEFAULT NULL COMMENT '放射物质防护措施1有2无',
  `field43` varchar(50) DEFAULT NULL COMMENT '物理因素',
  `field44` int(1) DEFAULT NULL COMMENT '物理因素防护措施1有2无',
  `field45` varchar(50) DEFAULT NULL COMMENT '化学物质',
  `field46` int(1) DEFAULT NULL COMMENT '化学物质防护措施1有2无',
  `field47` varchar(50) DEFAULT NULL COMMENT '其他',
  `field48` int(1) DEFAULT NULL COMMENT '其他防护措施1有2无',
  `field49` int(1) DEFAULT NULL COMMENT '口唇1红润2苍白3发绀4皲裂5疱疹',
  `field50` varchar(20) DEFAULT NULL COMMENT '齿列1正常2缺齿3龋齿4义齿(假牙)',
  `field51` varchar(20) DEFAULT NULL COMMENT '缺齿1',
  `field52` varchar(20) DEFAULT NULL COMMENT '缺齿2',
  `field53` varchar(20) DEFAULT NULL COMMENT '缺齿3',
  `field54` varchar(20) DEFAULT NULL COMMENT '缺齿4',
  `field55` varchar(20) DEFAULT NULL COMMENT '龋齿1',
  `field56` varchar(20) DEFAULT NULL COMMENT '龋齿2',
  `field57` varchar(20) DEFAULT NULL COMMENT '龋齿3',
  `field58` varchar(20) DEFAULT NULL COMMENT '龋齿4',
  `field59` varchar(20) DEFAULT NULL COMMENT '义齿1',
  `field60` varchar(20) DEFAULT NULL COMMENT '义齿2',
  `field61` varchar(20) DEFAULT NULL COMMENT '义齿3',
  `field62` varchar(20) DEFAULT NULL COMMENT '义齿4',
  `field63` int(1) DEFAULT NULL COMMENT '咽部1无充血2充血3淋巴滤泡增生',
  `field64` varchar(20) DEFAULT NULL COMMENT '左眼视力',
  `field65` varchar(20) DEFAULT NULL COMMENT '右眼视力',
  `field66` varchar(20) DEFAULT NULL COMMENT '左眼矫正视力',
  `field67` varchar(20) DEFAULT NULL COMMENT '右眼矫正视力',
  `field68` int(1) DEFAULT NULL COMMENT '听力1听见2听不清或无法听见',
  `field69` int(1) DEFAULT NULL COMMENT '运动功能1可顺利完成2无法独立完成其中任何一个动作',
  `field70` int(1) DEFAULT NULL COMMENT '眼底1正常2异常',
  `field71` int(1) DEFAULT NULL COMMENT '皮肤1正常2潮红3苍白4发绀5黄染6色素沉着7其他',
  `field72` int(1) DEFAULT NULL COMMENT '巩膜1正常2黄染3充血4其他',
  `field73` int(1) DEFAULT NULL COMMENT '淋巴结1未触及2锁骨上3腋窝4其他',
  `field74` int(1) DEFAULT NULL COMMENT '桶状胸1否2是',
  `field75` int(1) DEFAULT NULL COMMENT '呼吸音1正常2异常',
  `field76` int(1) DEFAULT NULL COMMENT '罗音1无2干罗音3湿罗音4其他',
  `field77` varchar(20) DEFAULT NULL COMMENT '心率',
  `field78` int(1) DEFAULT NULL COMMENT '心律1齐2不齐3绝对不齐',
  `field79` int(1) DEFAULT NULL COMMENT '杂音1无2有',
  `field80` int(1) DEFAULT NULL COMMENT '压痛1无2有',
  `field81` int(1) DEFAULT NULL COMMENT '包块1无2有',
  `field82` int(1) DEFAULT NULL COMMENT '肝大1无2有',
  `field83` int(1) DEFAULT NULL COMMENT '脾大1无2有',
  `field84` int(1) DEFAULT NULL COMMENT '移动性浊音1无2有',
  `field85` int(1) DEFAULT NULL COMMENT '下肢水肿1无2单侧3双侧不对称4双侧对称',
  `field86` int(1) DEFAULT NULL COMMENT '足背动脉搏动1未触及2触及双侧对称3触及左侧弱或消失4触及右侧弱或消失',
  `field87` int(1) DEFAULT NULL COMMENT '肛门指诊1未及异常2触痛3包块4前列腺异常5其他',
  `field88` int(1) DEFAULT NULL COMMENT '乳腺1未见异常2乳房切除3异常泌乳4乳腺包块5其他',
  `field89` int(1) DEFAULT NULL COMMENT '妇科外阴1未见异常2异常',
  `field90` int(1) DEFAULT NULL COMMENT '妇科阴道1未见异常2异常',
  `field91` int(1) DEFAULT NULL COMMENT '妇科宫颈1未见异常2异常',
  `field92` int(1) DEFAULT NULL COMMENT '妇科宫体1未见异常2异常',
  `field93` int(1) DEFAULT NULL COMMENT '妇科附件1未见异常2异常',
  `field94` varchar(60) DEFAULT NULL COMMENT '妇科其他',
  `field95` int(1) DEFAULT NULL COMMENT 'ABO1A型2B型3O型4AB型',
  `field96` int(1) DEFAULT NULL COMMENT 'RH1是2否3不详',
  `field97` varchar(20) DEFAULT NULL COMMENT '血红蛋白',
  `field98` varchar(20) DEFAULT NULL COMMENT '白细胞',
  `field99` varchar(20) DEFAULT NULL COMMENT '血小板',
  `field100` varchar(50) DEFAULT NULL COMMENT '血常规其他',
  `field101` varchar(50) DEFAULT NULL COMMENT '尿蛋白',
  `field102` varchar(50) DEFAULT NULL COMMENT '尿糖',
  `field103` varchar(50) DEFAULT NULL COMMENT '尿酮体',
  `field104` varchar(50) DEFAULT NULL COMMENT '尿潜血',
  `field105` varchar(50) DEFAULT NULL COMMENT '尿其他',
  `field106` varchar(50) DEFAULT NULL COMMENT '空腹血糖mmol/L',
  `field107` varchar(50) DEFAULT NULL COMMENT '空腹血糖mg/dL',
  `field108` varchar(50) DEFAULT NULL COMMENT '同型半胱氨酸',
  `field109` varchar(50) DEFAULT NULL COMMENT '尿微量蛋白',
  `field110` int(1) DEFAULT NULL COMMENT '大便潜血1阴性2阳性',
  `field111` varchar(50) DEFAULT NULL COMMENT '糖化血红蛋白',
  `field112` int(1) DEFAULT NULL COMMENT '乙型肝炎表面抗原1阴性2阳性',
  `field113` varchar(50) DEFAULT NULL COMMENT '乙肝mg/dL',
  `field114` varchar(50) DEFAULT NULL COMMENT '血清谷丙转氨酶',
  `field115` varchar(50) DEFAULT NULL COMMENT '血清谷草转氨酶',
  `field116` varchar(50) DEFAULT NULL COMMENT '白蛋白',
  `field117` varchar(50) DEFAULT NULL COMMENT '总胆红素',
  `field118` varchar(50) DEFAULT NULL COMMENT '结合胆红素',
  `field119` varchar(50) DEFAULT NULL COMMENT '血清肌酐',
  `field120` varchar(50) DEFAULT NULL COMMENT '血尿素氮',
  `field121` varchar(50) DEFAULT NULL COMMENT '血钾浓度1',
  `field122` varchar(50) DEFAULT NULL COMMENT '血钾浓度2',
  `field123` varchar(50) DEFAULT NULL COMMENT '总胆固醇',
  `field124` varchar(50) DEFAULT NULL COMMENT '甘油三酯',
  `field125` varchar(50) DEFAULT NULL COMMENT '低密度',
  `field126` varchar(50) DEFAULT NULL COMMENT '高密度',
  `field127` varchar(50) DEFAULT NULL COMMENT '心电图1正常2ST段改变3陈旧性心肌梗塞4窦性心动过速5窦性心动过缓6早搏7房颤8房室传导阻滞9其他',
  `field128` varchar(1000) DEFAULT NULL COMMENT '心电图其他',
  `field129` int(1) DEFAULT NULL COMMENT '胸部X片1正常2异常',
  `field130` int(1) DEFAULT NULL COMMENT '腹部B超1正常2异常',
  `field131` varchar(100) DEFAULT NULL COMMENT '妇科异常1',
  `field132` int(1) DEFAULT NULL COMMENT '其他1正常2异常',
  `field133` varchar(50) DEFAULT NULL COMMENT '腹部其他',
  `field134` int(1) DEFAULT NULL COMMENT '宫颈涂片1正常2异常',
  `field135` varchar(50) DEFAULT NULL COMMENT '宫颈涂片',
  `field136` varchar(50) DEFAULT NULL COMMENT '其他2',
  `field137` varchar(50) DEFAULT NULL COMMENT '脑血管疾病1未发现2缺血性卒中3脑出血4蛛网膜下腔出血5短暂性脑缺血6其他',
  `field138` varchar(50) DEFAULT NULL COMMENT '脑血管疾病其他',
  `field139` varchar(50) DEFAULT NULL COMMENT '肾脏疾病1未发现2糖尿病肾病3肾功能衰竭4急性肾炎5慢性肾炎6其他',
  `field140` varchar(50) DEFAULT NULL COMMENT '肾脏疾病其他',
  `field141` varchar(50) DEFAULT NULL COMMENT '心脏疾病1 未发现 2 心肌梗死 3 心绞痛 4 冠状动脉血运重建 5 充血性心力衰竭 6 心前区疼痛 7 其他',
  `field142` varchar(50) DEFAULT NULL COMMENT '心脏疾病病其他',
  `field143` varchar(50) DEFAULT NULL COMMENT '眼部疾病1未发现2视网膜出血或渗出3视乳头水肿4白内障5其他',
  `field144` varchar(50) DEFAULT NULL COMMENT '眼部疾病其他',
  `field145` varchar(50) DEFAULT NULL COMMENT '神经系统疾病1未发现2阿尔茨海默症(老年痴呆症)3帕金森病4其他',
  `field146` varchar(50) DEFAULT NULL COMMENT '神经系统疾病其他',
  `field147` varchar(50) DEFAULT NULL COMMENT '其他系统疾病1未发现2糖尿病3慢性支气管炎4慢性阻塞性肺气肿5恶性肿瘤6老年性骨关节病7其他',
  `field148` varchar(50) DEFAULT NULL COMMENT '其他系统疾病其他',
  `field149` timestamp NULL DEFAULT NULL COMMENT '入出院日期1',
  `field150` timestamp NULL DEFAULT NULL COMMENT '入出院日期2',
  `field151` timestamp NULL DEFAULT NULL COMMENT '入出院日期3',
  `field152` timestamp NULL DEFAULT NULL COMMENT '入出院日期4',
  `field153` varchar(100) DEFAULT NULL COMMENT '原因1',
  `field154` varchar(100) DEFAULT NULL COMMENT '原因2',
  `field155` varchar(100) DEFAULT NULL COMMENT '医疗机构名称1',
  `field156` varchar(100) DEFAULT NULL COMMENT '医疗机构名称2',
  `field157` varchar(100) DEFAULT NULL COMMENT '病案号1',
  `field158` varchar(100) DEFAULT NULL COMMENT '病案号2',
  `field159` timestamp NULL DEFAULT NULL COMMENT '建/撤床日期1',
  `field160` timestamp NULL DEFAULT NULL COMMENT '建/撤床日期2',
  `field161` timestamp NULL DEFAULT NULL COMMENT '建/撤床日期3',
  `field162` timestamp NULL DEFAULT NULL COMMENT '建/撤床日期4',
  `field163` varchar(100) DEFAULT NULL COMMENT '家庭病床史原因1',
  `field164` varchar(100) DEFAULT NULL COMMENT '家庭病床史原因2',
  `field165` varchar(100) DEFAULT NULL COMMENT '家庭病床史医疗机构名称1',
  `field166` varchar(100) DEFAULT NULL COMMENT '家庭病床史医疗机构名称2',
  `field167` varchar(100) DEFAULT NULL COMMENT '家庭病床史病案号1',
  `field168` varchar(100) DEFAULT NULL COMMENT '家庭病床史病案号2',
  `field169` varchar(100) DEFAULT NULL COMMENT '药物名称1',
  `field170` int(1) DEFAULT NULL COMMENT '用法(1)1口服2皮下注射3静脉注射4肌肉注射',
  `field171` varchar(50) DEFAULT NULL COMMENT '用量1',
  `field172` int(1) DEFAULT NULL COMMENT '用药时间(1)1 1周 2 2周 3 3周 4 1个月 5 2个月 6 3个月 7 4个月 8 5个月 9 6个月 10 7个月 11 8个月 12 9个月 13 10个月 14 11个月 15 1年 16 2年 17 3年 18 4年 19 5年',
  `field173` int(1) DEFAULT NULL COMMENT '服药依从性(1)1规律2间断3不服药',
  `field174` varchar(100) DEFAULT NULL COMMENT '药物名称2',
  `field175` int(1) DEFAULT NULL COMMENT '用法(2)1口服2皮下注射3静脉注射4肌肉注射',
  `field176` varchar(50) DEFAULT NULL COMMENT '用量2',
  `field177` int(1) DEFAULT NULL COMMENT '用药时间(2)1 1周 2 2周 3 3周 4 1个月 5 2个月 6 3个月 7 4个月 8 5个月 9 6个月 10 7个月 11 8个月 12 9个月 13 10个月 14 11个月 15 1年 16 2年 17 3年 18 4年 19 5年',
  `field178` int(1) DEFAULT NULL COMMENT '服药依从性(2)1规律2间断3不服药',
  `field179` varchar(100) DEFAULT NULL COMMENT '药物名称3',
  `field180` int(1) DEFAULT NULL COMMENT '用法(3)1口服2皮下注射3静脉注射4肌肉注射',
  `field181` varchar(50) DEFAULT NULL COMMENT '用量3',
  `field182` int(1) DEFAULT NULL COMMENT '用药时间(3)1 1周 2 2周 3 3周 4 1个月 5 2个月 6 3个月 7 4个月 8 5个月 9 6个月 10 7个月 11 8个月 12 9个月 13 10个月 14 11个月 15 1年 16 2年 17 3年 18 4年 19 5年',
  `field183` int(1) DEFAULT NULL COMMENT '服药依从性(3)1规律2间断3不服药',
  `field184` varchar(100) DEFAULT NULL COMMENT '药物名称4',
  `field185` int(1) DEFAULT NULL COMMENT '用法(4)1口服2皮下注射3静脉注射4肌肉注射',
  `field186` varchar(50) DEFAULT NULL COMMENT '用量4',
  `field187` int(1) DEFAULT NULL COMMENT '用药时间(4)1 1周 2 2周 3 3周 4 1个月 5 2个月 6 3个月 7 4个月 8 5个月 9 6个月 10 7个月 11 8个月 12 9个月 13 10个月 14 11个月 15 1年 16 2年 17 3年 18 4年 19 5年',
  `field188` int(1) DEFAULT NULL COMMENT '服药依从性(4)1规律2间断3不服药',
  `field189` varchar(100) DEFAULT NULL COMMENT '药物名称5',
  `field190` int(1) DEFAULT NULL COMMENT '用法(5)1口服2皮下注射3静脉注射4肌肉注射',
  `field191` varchar(50) DEFAULT NULL COMMENT '用量5',
  `field192` int(1) DEFAULT NULL COMMENT '用药时间(5)1 1周 2 2周 3 3周 4 1个月 5 2个月 6 3个月 7 4个月 8 5个月 9 6个月 10 7个月 11 8个月 12 9个月 13 10个月 14 11个月 15 1年 16 2年 17 3年 18 4年 19 5年',
  `field193` int(1) DEFAULT NULL COMMENT '服药依从性(5)1规律2间断3不服药',
  `field194` varchar(100) DEFAULT NULL COMMENT '药物名称6',
  `field195` int(1) DEFAULT NULL COMMENT '用法(6)1口服2皮下注射3静脉注射4肌肉注射',
  `field196` varchar(50) DEFAULT NULL COMMENT '用量6',
  `field197` int(1) DEFAULT NULL COMMENT '用药时间(6)1 1周 2 2周 3 3周 4 1个月 5 2个月 6 3个月 7 4个月 8 5个月 9 6个月 10 7个月 11 8个月 12 9个月 13 10个月 14 11个月 15 1年 16 2年 17 3年 18 4年 19 5年',
  `field198` int(1) DEFAULT NULL COMMENT '服药依从性(6)1规律2间断3不服药',
  `field199` varchar(100) DEFAULT NULL COMMENT '非免疫名称1',
  `field200` timestamp NULL DEFAULT NULL COMMENT '接种日期1',
  `field201` varchar(50) DEFAULT NULL COMMENT '接种机构1',
  `field202` varchar(100) DEFAULT NULL COMMENT '非免疫名称2',
  `field203` timestamp NULL DEFAULT NULL COMMENT '接种日期2',
  `field204` varchar(50) DEFAULT NULL COMMENT '接种机构2',
  `field205` varchar(100) DEFAULT NULL COMMENT '非免疫名称3',
  `field206` timestamp NULL DEFAULT NULL COMMENT '接种日期3',
  `field207` varchar(50) DEFAULT NULL COMMENT '接种机构3',
  `field208` int(1) DEFAULT NULL COMMENT '健康评价1体检无异常2有异常',
  `field209` varchar(1000) DEFAULT NULL COMMENT '健康评价异常1',
  `field210` varchar(300) DEFAULT NULL COMMENT 'B超图片1',
  `field211` varchar(1000) DEFAULT NULL COMMENT '健康评价异常2',
  `field212` varchar(1000) DEFAULT NULL COMMENT '健康评价异常3',
  `field213` varchar(1000) DEFAULT NULL COMMENT '健康评价异常4',
  `field214` varchar(50) DEFAULT NULL COMMENT '健康指导1定期随访2纳入慢性病患者健康管理3建议复查4建议转诊',
  `field215` varchar(50) DEFAULT NULL COMMENT '危险因素控制1戒烟2健康饮酒3饮食4锻炼5减体重6建议接种疫苗7其他',
  `field216` varchar(50) DEFAULT NULL COMMENT '目标',
  `field217` varchar(50) DEFAULT NULL COMMENT '建议接种疫苗',
  `field218` varchar(50) DEFAULT NULL COMMENT '健康体检其他',
  `field219` varchar(50) DEFAULT NULL COMMENT 'BMI',
  `field220` varchar(100) DEFAULT NULL COMMENT '妇科异常2',
  `field221` varchar(100) DEFAULT NULL COMMENT '妇科异常3',
  `field222` varchar(50) DEFAULT NULL COMMENT '红细胞计数',
  `field223` varchar(50) DEFAULT NULL COMMENT '红细胞压积',
  `field224` varchar(50) DEFAULT NULL COMMENT '淋巴细胞百分比',
  `field225` varchar(50) DEFAULT NULL COMMENT '中间细胞百分比',
  `field226` varchar(50) DEFAULT NULL COMMENT '中性粒细胞百分比',
  `field227` varchar(50) DEFAULT NULL COMMENT '平均红细胞血红蛋白浓度',
  `field228` varchar(50) DEFAULT NULL COMMENT '平均红细胞体积',
  `field229` varchar(50) DEFAULT NULL COMMENT '平均红细胞血红蛋白含量',
  `field230` varchar(50) DEFAULT NULL COMMENT '血小板分布宽度',
  `field231` varchar(50) DEFAULT NULL COMMENT '红细胞分布宽度变异系数',
  `field232` varchar(50) DEFAULT NULL COMMENT '平均血小板体积',
  `field233` varchar(50) DEFAULT NULL COMMENT '血小板压积',
  `field234` varchar(50) DEFAULT NULL COMMENT '淋巴细胞绝对值',
  `field235` varchar(50) DEFAULT NULL COMMENT '中间细胞绝对值',
  `field236` varchar(50) DEFAULT NULL COMMENT '中性粒细胞绝对值',
  `field237` varchar(50) DEFAULT NULL COMMENT '尿胆红素',
  `field238` varchar(50) DEFAULT NULL COMMENT '尿胆原',
  `field239` varchar(50) DEFAULT NULL COMMENT '亚硝酸盐',
  `field240` varchar(50) DEFAULT NULL COMMENT '尿白细胞',
  `field241` varchar(50) DEFAULT NULL COMMENT '尿比重',
  `field242` varchar(50) DEFAULT NULL COMMENT '尿酸碱值',
  `field243` varchar(50) DEFAULT NULL COMMENT '红细胞分布宽度标准差',
  `field244` varchar(1000) DEFAULT NULL COMMENT '超声所见',
  `field245` varchar(1000) DEFAULT NULL COMMENT '超声提示',
  `field246` varchar(300) DEFAULT NULL COMMENT '心电图图片',
  `field247` varchar(20) DEFAULT NULL COMMENT ' 尿常规检查员',
  `field248` varchar(20) DEFAULT NULL COMMENT ' 生化检查员',
  `field249` varchar(20) DEFAULT NULL COMMENT ' 心电图检查员',
  `field250` varchar(20) DEFAULT NULL COMMENT ' B超检查员',
  `field251` varchar(300) DEFAULT NULL COMMENT 'B超图片2',
  `field252` varchar(300) DEFAULT NULL COMMENT 'B超图片3',
  `field253` varchar(300) DEFAULT NULL COMMENT 'B超图片4',
  `field254` varchar(300) DEFAULT NULL COMMENT 'B超图片5',
  `field255` varchar(300) DEFAULT NULL COMMENT 'B超图片6',
  `field256` varchar(100) DEFAULT NULL COMMENT '妇科异常4',
  `field257` varchar(100) DEFAULT NULL COMMENT '妇科异常5',
  `field258` varchar(50) DEFAULT NULL COMMENT '尿蛋白单位',
  `field259` varchar(50) DEFAULT NULL COMMENT '尿糖单位',
  `field260` varchar(50) DEFAULT NULL COMMENT '尿胆红素单位',
  `field261` varchar(50) DEFAULT NULL COMMENT '尿胆原单位',
  `field262` varchar(50) DEFAULT NULL COMMENT '尿潜血单位',
  `field263` varchar(50) DEFAULT NULL COMMENT '尿酮体单位',
  `field264` varchar(50) DEFAULT NULL COMMENT '亚硝酸盐单位',
  `field265` varchar(50) DEFAULT NULL COMMENT '尿白细胞单位',
  `field266` varchar(50) DEFAULT NULL COMMENT '尿比重单位',
  `field267` varchar(50) DEFAULT NULL COMMENT '尿酸碱值单位',
  `field268` varchar(50) DEFAULT NULL COMMENT '血管疾病1未发现2夹层动脉瘤3动脉闭塞性疾病4其他',
  `field269` varchar(50) DEFAULT NULL COMMENT '血管疾病其他',
  `pid` int(11) NOT NULL COMMENT '病人',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  UNIQUE KEY `pid` (`pid`),
  CONSTRAINT `pat_che_FK` FOREIGN KEY (`pid`) REFERENCES `patients` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='健康体检表';

CREATE TABLE `hislog` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `hcid` int(11) DEFAULT NULL COMMENT '卫生所',
  `regionid` varchar(100) DEFAULT NULL COMMENT '区域ID',
  `regioncode` varchar(100) DEFAULT NULL COMMENT '区域CODE',
  `dcode` varchar(100) DEFAULT NULL COMMENT '医生编码',
  `dname` varchar(100) DEFAULT NULL COMMENT '医生姓名',
  `sucnum` int(11) DEFAULT NULL COMMENT '成功条数',
  `errnum` int(11) DEFAULT NULL COMMENT '失败条数',
  `erromsg` longtext COMMENT '失败信息',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  KEY `hislog_healthc_FK` (`hcid`),
  CONSTRAINT `hislog_healthc_FK` FOREIGN KEY (`hcid`) REFERENCES `healthcenters` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='省平台上传数据记录表';

CREATE TABLE `selfcare` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `field1` int(1) DEFAULT NULL COMMENT '进餐：使用餐具将饭菜送人口、咀嚼、吞咽等活动:1独立完成2-----3需要协助，如切碎、搅拌食物等4完全需要帮助',
  `field2` int(1) DEFAULT NULL COMMENT '梳洗：梳头、洗脸、刷牙、剃须洗澡等活动:1独立完成2能独立地洗头、梳头、洗脸、刷牙、剃须等；洗澡需要协助3在协助下和适当的时间内，能完成部分梳洗活动4完全需要帮助',
  `field3` int(1) DEFAULT NULL COMMENT '穿衣：穿衣裤、袜子、鞋子等活动:1独立完成2-----3需要协助,在适当的时间内，完成部分穿衣4完全需要帮助',
  `field4` int(1) DEFAULT NULL COMMENT '如厕：小便、大便等活动及自控1不需协助，可自控2偶尔失禁，但基本上能如厕或使用便具3经常失禁，在很多提示和协助下尚能如厕或使用便具4完全失禁，完全需要帮助',
  `field5` int(1) DEFAULT NULL COMMENT '活动：站立、室内行走、上下楼梯、户外活动:1独立完成所有活动2借助较小的外力或辅助装置能完成站立、行走、上下楼梯等3借助较大的外力才能完成站立、行走，不能上下楼梯4借助较大的外力才能完成站立、行走，不能上下楼梯',
  `field6` varchar(20) DEFAULT NULL COMMENT '总分',
  `field7` varchar(100) DEFAULT NULL COMMENT '下次随访目标',
  `field8` timestamp NULL DEFAULT NULL COMMENT '下次随访日期',
  `field9` varchar(200) DEFAULT NULL COMMENT '评估结论',
  `pid` int(11) NOT NULL COMMENT '病人',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  UNIQUE KEY `pid` (`pid`),
  CONSTRAINT `pat_self_FK` FOREIGN KEY (`pid`) REFERENCES `patients` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='自理能力表';

CREATE TABLE `tcm` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `field1` int(1) DEFAULT NULL COMMENT '（1）您精力充沛吗？（指精神头足，乐于做事）:1没有2很少3有时4经常5总是',
  `field2` int(1) DEFAULT NULL COMMENT '（2）您容易疲乏吗？（指体力如何，是否稍微活动一下或做一点家务劳动就感到累）:1没有2很少3有时4经常5总是',
  `field3` int(1) DEFAULT NULL COMMENT '（3）您容易气短，呼吸短促，接不上气吗？:1没有2很少3有时4经常5总是',
  `field4` int(1) DEFAULT NULL COMMENT '（4）您说话声音低弱无力吗？（指说话没有力气）:1没有2很少3有时4经常5总是',
  `field5` int(1) DEFAULT NULL COMMENT '（5）您感到闷闷不乐、情绪低沉吗？（指心情不愉快，情绪低落）:1没有2很少3有时4经常5总是',
  `field6` int(1) DEFAULT NULL COMMENT '（6）您容易精神紧张、焦虑不安吗？（指遇事是否心情紧张）:1没有2很少3有时4经常5总是',
  `field7` int(1) DEFAULT NULL COMMENT '（7）您因为生活状态改变而感到孤独、失落吗？:1没有2很少3有时4经常5总是',
  `field8` int(1) DEFAULT NULL COMMENT '（8）您容易感到害怕或受到惊吓吗？:1没有2很少3有时4经常5总是',
  `field9` int(1) DEFAULT NULL COMMENT '（9）您感到身体超重不轻松吗？（感觉身体沉重）:1没有2很少3有时4经常5总是',
  `field10` int(1) DEFAULT NULL COMMENT '（10）您眼睛干涩吗？:1没有2很少3有时4经常5总是',
  `field11` int(1) DEFAULT NULL COMMENT '（11）您手脚发凉吗？（不包含因周围温度低或穿的少导致的手脚发冷）:1没有2很少3有时4经常5总是',
  `field12` int(1) DEFAULT NULL COMMENT '（12）您胃脘部、背部或腰膝部怕冷吗？（指上腹部、背部、腰部或膝关节等，有一处或多处怕冷）:1没有2很少3有时4经常5总是',
  `field13` int(1) DEFAULT NULL COMMENT '（13）您比一般人耐受不了寒冷吗？（指比别人容易害怕冬天或是夏天的冷空调、电扇等）:1没有2很少3有时4经常5总是',
  `field14` int(1) DEFAULT NULL COMMENT '（14）您容易感冒吗？（指每年感冒的次数）:1没有2很少3有时4经常5总是',
  `field15` int(1) DEFAULT NULL COMMENT '（15）您没有感冒时也会鼻塞、流鼻涕吗？:1没有2很少3有时4经常5总是',
  `field16` int(1) DEFAULT NULL COMMENT '（16）您有口粘口腻，或睡眠打鼾吗？:1没有2很少3有时4经常5总是',
  `field17` int(1) DEFAULT NULL COMMENT '（17）您容易过敏（对药物、食物、气味、花粉或在季节交替、气候变化时）吗？:1没有2很少3有时4经常5总是',
  `field18` int(1) DEFAULT NULL COMMENT '（18）您的皮肤容易起荨麻疹吗？（包括风团、风疹块、风疙瘩）:1没有2很少3有时4经常5总是',
  `field19` int(1) DEFAULT NULL COMMENT '（19）您的皮肤在不知不觉中会出现青紫瘀块、皮下出血吗？（指皮肤在没有外伤的情况下出现青一块紫一块的情况）:1没有2很少3有时4经常5总是',
  `field20` int(1) DEFAULT NULL COMMENT '（20）您的皮肤一抓就红，并出现抓痕吗？（指被指甲或钝物划过后皮肤的反应）:1没有2很少3有时4经常5总是',
  `field21` int(1) DEFAULT NULL COMMENT '（21）您皮肤或口唇干吗？:1没有2很少3有时4经常5总是',
  `field22` int(1) DEFAULT NULL COMMENT '（22）您有肢体麻木或固定部位疼痛的感觉吗？:1没有2很少3有时4经常5总是',
  `field23` int(1) DEFAULT NULL COMMENT '（23）您面部或鼻部有油腻感或者油亮发光吗？（指脸上或鼻子）:1没有2很少3有时4经常5总是',
  `field24` int(1) DEFAULT NULL COMMENT '（24）您面色或目眶晦暗，或出现褐色斑块/斑点吗？:1没有2很少3有时4经常5总是',
  `field25` int(1) DEFAULT NULL COMMENT '（25）您有皮肤湿疹、疮疖吗？:1没有2很少3有时4经常5总是',
  `field26` int(1) DEFAULT NULL COMMENT '（26）您感到口干咽燥、总想喝水吗？:1没有2很少3有时4经常5总是',
  `field27` int(1) DEFAULT NULL COMMENT '（27）您感到口苦或嘴里有异味吗？(指口苦或口臭):1没有2很少3有时4经常5总是',
  `field28` int(1) DEFAULT NULL COMMENT '（28）您腹部肥大吗？（指腹部脂肪肥厚）:1没有2很少3有时4经常5总是',
  `field29` int(1) DEFAULT NULL COMMENT '（29）您吃(喝)凉的东西会感到不舒服或者怕吃(喝)凉的东西吗？(指不喜欢吃凉的食物，或吃了凉的食物后会不舒服):1没有2很少3有时4经常5总是',
  `field30` int(1) DEFAULT NULL COMMENT '（30）您有大便粘滞不爽、解不尽的感觉吗？（大便容易粘在马桶或便坑壁上）:1没有2很少3有时4经常5总是',
  `field31` int(1) DEFAULT NULL COMMENT '（31）您容易大便干燥吗？:1没有2很少3有时4经常5总是',
  `field32` int(1) DEFAULT NULL COMMENT '（32）您舌苔厚腻或有舌苔厚厚的感觉吗？（如果自我感觉不清楚可由调查员观察后填写）:1没有2很少3有时4经常5总是',
  `field33` int(1) DEFAULT NULL COMMENT '（33）您舌下静脉瘀紫或增粗吗？(可以调查员辅助观察后填写):1没有2很少3有时4经常5总是',
  `field34` varchar(20) DEFAULT NULL COMMENT '气虚质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field35` varchar(20) DEFAULT NULL COMMENT '阳虚质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field36` varchar(20) DEFAULT NULL COMMENT '阴虚质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field37` varchar(20) DEFAULT NULL COMMENT '痰湿质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field38` varchar(20) DEFAULT NULL COMMENT '湿热质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field39` varchar(20) DEFAULT NULL COMMENT '血瘀质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field40` varchar(20) DEFAULT NULL COMMENT '气郁质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field41` varchar(20) DEFAULT NULL COMMENT '特禀质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field42` varchar(20) DEFAULT NULL COMMENT '平和质:1是2倾向是3情志调摄4饮食调养5起居调摄6运动保健7穴位保健',
  `field43` varchar(100) DEFAULT NULL COMMENT '气虚质其他',
  `field44` varchar(100) DEFAULT NULL COMMENT '阳虚质其他',
  `field45` varchar(100) DEFAULT NULL COMMENT '阴虚质其他',
  `field46` varchar(100) DEFAULT NULL COMMENT '痰湿质其他',
  `field47` varchar(100) DEFAULT NULL COMMENT '湿热质其他',
  `field48` varchar(100) DEFAULT NULL COMMENT '血瘀质其他',
  `field49` varchar(100) DEFAULT NULL COMMENT '气郁质其他',
  `field50` varchar(100) DEFAULT NULL COMMENT '特禀质其他',
  `field51` varchar(100) DEFAULT NULL COMMENT '平和质其他',
  `field52` varchar(20) DEFAULT NULL COMMENT '随访医生',
  `field53` varchar(20) DEFAULT NULL COMMENT '气虚质得分',
  `field54` varchar(20) DEFAULT NULL COMMENT '阳虚质得分',
  `field55` varchar(20) DEFAULT NULL COMMENT '阴虚质得分',
  `field56` varchar(20) DEFAULT NULL COMMENT '痰湿质得分',
  `field57` varchar(20) DEFAULT NULL COMMENT '湿热质得分',
  `field58` varchar(20) DEFAULT NULL COMMENT '血瘀质得分',
  `field59` varchar(20) DEFAULT NULL COMMENT '气郁质得分',
  `field60` varchar(20) DEFAULT NULL COMMENT '特禀质得分',
  `field61` varchar(20) DEFAULT NULL COMMENT '平和质得分',
  `pid` int(11) NOT NULL COMMENT '病人',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  UNIQUE KEY `pid` (`pid`),
  CONSTRAINT `pat_TCM_FK` FOREIGN KEY (`pid`) REFERENCES `patients` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='中医体质';

CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `userName` varchar(20) NOT NULL COMMENT '用户名',
  `userPassword` varchar(100) NOT NULL COMMENT '密码',
  `province` int(11) DEFAULT NULL COMMENT '省',
  `city` int(11) DEFAULT NULL COMMENT '市',
  `county` int(11) DEFAULT NULL COMMENT '县',
  `hcid` int(11) DEFAULT NULL COMMENT '卫生所',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  UNIQUE KEY `userName` (`userName`),
  KEY `heals_users_FK` (`hcid`),
  CONSTRAINT `heals_users_FK` FOREIGN KEY (`hcid`) REFERENCES `healthcenters` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';

CREATE TABLE `doctorsign` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `field1` varchar(50) DEFAULT NULL COMMENT '团队长名称',
  `field2` varchar(100) DEFAULT NULL COMMENT '团队长地址',
  `field3` varchar(50) DEFAULT NULL COMMENT '团队长电话',
  `field4` varchar(50) DEFAULT NULL COMMENT '团队医生名称',
  `field5` varchar(100) DEFAULT NULL COMMENT '团队医生地址',
  `field6` varchar(50) DEFAULT NULL COMMENT '团队医生电话',
  `field7` varchar(50) DEFAULT NULL COMMENT '护士名称',
  `field8` varchar(100) DEFAULT NULL COMMENT '护士地址',
  `field9` varchar(50) DEFAULT NULL COMMENT '护士电话',
  `field10` varchar(50) DEFAULT NULL COMMENT '公务人员名称',
  `field11` varchar(100) DEFAULT NULL COMMENT '公务人员地址',
  `field12` varchar(50) DEFAULT NULL COMMENT '公务人员电话',
  `field13` varchar(50) DEFAULT NULL COMMENT '其他人员名称',
  `field14` varchar(100) DEFAULT NULL COMMENT '其他人员地址',
  `field15` varchar(50) DEFAULT NULL COMMENT '其他人员电话',
  `field16` varchar(50) DEFAULT NULL COMMENT '其他人员2名称',
  `field17` varchar(100) DEFAULT NULL COMMENT '其他人员2地址',
  `field18` varchar(50) DEFAULT NULL COMMENT '其他人员2电话',
  `field19` varchar(50) DEFAULT NULL COMMENT '其他人员3名称',
  `field20` varchar(100) DEFAULT NULL COMMENT '其他人员3地址',
  `field21` varchar(50) DEFAULT NULL COMMENT '其他人员3电话',
  `field22` varchar(100) DEFAULT NULL COMMENT '监督单位',
  `field23` varchar(50) DEFAULT NULL COMMENT '监督电话',
  `field24` varchar(20) DEFAULT NULL COMMENT '服务对象类型:1孕妇2⼉童3⾼⾎压4糖尿病5⽼年⼈6慢阻肺7计⽣特殊家庭8贫困⼈⼝9其它',
  `field25` varchar(100) DEFAULT NULL COMMENT '服务类型',
  `field26` varchar(20) DEFAULT NULL COMMENT '费用',
  `field27` varchar(100) DEFAULT NULL COMMENT '签字盖章',
  `hcid` int(11) DEFAULT NULL COMMENT '卫生所',
  `createDate` timestamp NULL DEFAULT NULL COMMENT '创建日期',
  `updateDate` timestamp NULL DEFAULT NULL COMMENT '修改日期',
  PRIMARY KEY (`id`),
  KEY `heals_doctor_FK` (`hcid`),
  CONSTRAINT `heals_doctor_FK ` FOREIGN KEY (`hcid`) REFERENCES `healthcenters` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='家医签约表';